-- The schema as it stands, and the first migration Drizzle owns.
--
-- Seventeen hand-written files made this schema, one ticket at a time. They are not
-- replayed here: this is `pg_dump --schema-only` of the database they produced, verified
-- object-for-object against it, so what a fresh clone builds is exactly what the Cluster
-- already runs. Their reasoning is not lost — it is in `docs/adr/`, in `CONTEXT.md`, and
-- in the `comment on` statements below, which is where a reader looks anyway.
--
-- **It is a dump and not a generated file on purpose.** `drizzle-kit pull` was tried first
-- and is lossy against this schema: it scrambles composite index column order, drops `desc`
-- and `nulls last`, drops `nulls not distinct` — which is an invariant, not a hint — and
-- models neither the trigger function below nor its two triggers. See ADR-0009.
--
-- Everything after this file is generated by `drizzle-kit generate` from `db/schema.ts`,
-- except what Drizzle cannot express: the function and triggers are hand-written SQL here
-- and will be hand-written SQL in any migration that changes them.

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6


--
-- Name: volume_holds_one_position(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.volume_holds_one_position() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
  subject   uuid;
  in_series uuid;
  position  integer;
begin
  -- Two branches rather than one `case`, because PL/pgSQL resolves the fields of `new` in a
  -- whole expression against whichever row type fired it: `new.volume_id` written beside
  -- `new.id` fails on the `volume` trigger even where it is never reached.
  if tg_table_name = 'volume' then
    subject := new.id;
  else
    subject := new.volume_id;
  end if;

  select v.series_id, v.series_number into in_series, position
    from volume v
   where v.id = subject
     and v.series_id is not null
     and exists (select 1 from acquisition a
                  where a.volume_id = v.id and a.released_on is null);

  -- Not in a Series, or not in the house: there is no position to hold.
  if in_series is null then
    return null;
  end if;

  -- **The lock is what a unique index gave for free.** The index this replaces serialized
  -- two writers claiming one position; a query cannot, because neither transaction can see
  -- the other's uncommitted row and both would pass the test below. So the position itself
  -- is the lock: taken on the pair rather than on a table, held to the end of the
  -- transaction, and contended only by a second writer claiming the very same position.
  perform pg_advisory_xact_lock(hashtextextended(in_series::text || ':' || position, 0));

  if exists (
    select 1
      from volume other
     where other.id <> subject
       and other.series_id = in_series
       and other.series_number = position
       and exists (select 1 from acquisition a
                    where a.volume_id = other.id and a.released_on is null)
  ) then
    raise exception 'that position of the Series is already in the house'
      using errcode = 'unique_violation',
            constraint = 'volume_is_one_per_number_in_a_series';
  end if;

  return null;
end;
$$;


--
-- Name: FUNCTION volume_holds_one_position(); Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON FUNCTION public.volume_holds_one_position() IS 'One owned Volume per position per Series (ADR-0007). What #7 wrote as a partial unique index, restated across two tables now that ownership is an acquisition.';




--
-- Name: acquisition; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acquisition (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    volume_id uuid NOT NULL,
    acquired_on date,
    released_on date,
    price_paid numeric(10,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT acquisition_price_paid_is_not_negative CHECK (((price_paid IS NULL) OR (price_paid >= (0)::numeric))),
    CONSTRAINT acquisition_release_follows_acquisition CHECK (((released_on IS NULL) OR (acquired_on IS NULL) OR (released_on >= acquired_on)))
);


--
-- Name: TABLE acquisition; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.acquisition IS 'The explicit fact that a catalogued Volume is in the owner''s house, and until when. The Collection is the Volumes with an open acquisition (ADR-0007); a catalogued Volume with no open acquisition is known and not owned, which is what a Wish names.';


--
-- Name: COLUMN acquisition.acquired_on; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.acquisition.acquired_on IS 'When it came home, where the owner knows. The row is the fact, not this day.';


--
-- Name: COLUMN acquisition.released_on; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.acquisition.released_on IS 'Null is in the house, and the Collection. A day is an acquisition that ended.';


--
-- Name: COLUMN acquisition.price_paid; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.acquisition.price_paid IS 'What was paid for *this* acquisition, in euro.';


--
-- Name: binding; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.binding (
    id text NOT NULL,
    name text NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT binding_display_order_is_positive CHECK ((display_order > 0)),
    CONSTRAINT binding_id_is_a_slug CHECK ((id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text)),
    CONSTRAINT binding_name_is_not_blank CHECK (((name = btrim(name)) AND (name <> ''::text)))
);


--
-- Name: TABLE binding; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.binding IS 'How a Volume is bound. A property of the object, never of the reading: the medium a Story was read by belongs to a Reading, and the two words were the same word in the spreadsheets. Stored as data so that a new Binding is an insert.';


--
-- Name: COLUMN binding.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.binding.id IS 'Stable slug, and what MCP shows an external reader.';


--
-- Name: COLUMN binding.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.binding.name IS 'What the owner reads on screen.';


--
-- Name: credit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    story_id uuid NOT NULL,
    person_id uuid NOT NULL,
    role_id text CONSTRAINT credit_role_id_not_null1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE credit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.credit IS 'A person''s contribution to a Story in a named role. One person may hold both roles on the same Story, and the two are routinely different people.';


--
-- Name: credit_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_role (
    id text NOT NULL,
    name text NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT credit_role_display_order_is_positive CHECK ((display_order > 0)),
    CONSTRAINT credit_role_id_is_a_slug CHECK ((id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text)),
    CONSTRAINT credit_role_name_is_not_blank CHECK (((name = btrim(name)) AND (name <> ''::text)))
);


--
-- Name: TABLE credit_role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.credit_role IS 'The named role a person''s contribution to a Story is held in. Stored as data so that a colourist or a letterer is an insert; the word `author` is deliberately not among them, because it presumes a single role and silently drops the artist.';


--
-- Name: COLUMN credit_role.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.credit_role.id IS 'Stable slug, and what MCP shows an external reader.';


--
-- Name: declared_constraint; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.declared_constraint (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    path_id uuid,
    prose text NOT NULL,
    declared_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT declared_constraint_prose_is_not_blank CHECK (((prose = btrim(prose)) AND (prose <> ''::text)))
);


--
-- Name: TABLE declared_constraint; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.declared_constraint IS 'What the owner has declared about how they want to read, in prose. On a Path, or globally when path_id is null. Read through MCP as instructions to the external advisor, never interpreted here (ADR-0002).';


--
-- Name: COLUMN declared_constraint.path_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.declared_constraint.path_id IS 'The Path it holds over. Null is the global scope, not a missing value.';


--
-- Name: edition_note; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.edition_note (
    volume_id uuid NOT NULL,
    note text NOT NULL,
    written_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT edition_note_is_not_blank CHECK (((note = btrim(note)) AND (note <> ''::text)))
);


--
-- Name: TABLE edition_note; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.edition_note IS 'What the owner thinks of a Volume as an object. Not a score, and there is no column here that could hold one: it decides what to buy and never feeds recommendation (ADR-0001, CONTEXT.md).';


--
-- Name: COLUMN edition_note.note; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.edition_note.note IS 'Prose, and the whole of the judgement.';


--
-- Name: inbox_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inbox_entry (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    reported text NOT NULL,
    proposes text NOT NULL,
    reference text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    proposed_at timestamp with time zone DEFAULT now() NOT NULL,
    decided_at timestamp with time zone,
    outcome text,
    created_id uuid,
    CONSTRAINT inbox_entry_approval_names_what_it_created CHECK (((NOT (outcome IS DISTINCT FROM 'approved'::text)) = (created_id IS NOT NULL))),
    CONSTRAINT inbox_entry_details_is_a_document CHECK ((jsonb_typeof(details) = 'object'::text)),
    CONSTRAINT inbox_entry_is_decided_once CHECK (((decided_at IS NULL) = (outcome IS NULL))),
    CONSTRAINT inbox_entry_outcome_is_approved_or_rejected CHECK (((outcome IS NULL) OR (outcome = ANY (ARRAY['approved'::text, 'rejected'::text])))),
    CONSTRAINT inbox_entry_proposes_a_story_volume_or_series CHECK ((proposes = ANY (ARRAY['story'::text, 'volume'::text, 'series'::text]))),
    CONSTRAINT inbox_entry_reference_is_not_blank CHECK (((reference = btrim(reference)) AND (reference <> ''::text))),
    CONSTRAINT inbox_entry_reported_is_not_blank CHECK (((reported = btrim(reported)) AND (reported <> ''::text)))
);


--
-- Name: TABLE inbox_entry; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.inbox_entry IS 'What an external assistant asked for and the owner has not decided yet (ADR-0005). Creating a Story, Volume or Series over MCP is impossible; the attempt lands here as a proposal, and approval is the act that creates the entity. A rejected entry leaves no trace in the domain, because this row is the only trace a proposal ever had.';


--
-- Name: COLUMN inbox_entry.reported; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.inbox_entry.reported IS 'What was said, in the words it was said in. The sheet''s Segnalazione.';


--
-- Name: COLUMN inbox_entry.proposes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.inbox_entry.proposes IS 'story, volume or series - the three ADR-0005 allows to be proposed. Not called type: Type is an attribute of a Story and lives in details.';


--
-- Name: COLUMN inbox_entry.reference; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.inbox_entry.reference IS 'The title or reference as given.';


--
-- Name: COLUMN inbox_entry.details; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.inbox_entry.details IS 'Everything else the assistant supplied, untrusted and unchecked. It becomes an argument to a verb at approval and meets that verb''s constraints there.';


--
-- Name: COLUMN inbox_entry.decided_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.inbox_entry.decided_at IS 'Null is waiting, and waiting is the Inbox.';


--
-- Name: COLUMN inbox_entry.created_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.inbox_entry.created_id IS 'The story, volume or series the approval created. Null on a rejected or waiting entry.';


--
-- Name: path; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.path (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    intent text,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT path_intent_is_not_blank CHECK (((intent IS NULL) OR (btrim(intent) <> ''::text))),
    CONSTRAINT path_name_is_not_blank CHECK (((name = btrim(name)) AND (name <> ''::text)))
);


--
-- Name: TABLE path; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.path IS 'An ordered route through Stories that the owner defines. Its order is the owner''s judgement and is derived from nothing; its intent is prose the external recommender reads (ADR-0002).';


--
-- Name: COLUMN path.intent; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.path.intent IS 'The owner''s own words about what the route is for. Data, read over MCP.';


--
-- Name: COLUMN path.active; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.path.active IS 'The Reading list composes itself from the active Paths only.';


--
-- Name: path_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.path_item (
    path_id uuid NOT NULL,
    story_id uuid NOT NULL,
    "position" numeric NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT path_item_position_is_positive CHECK (("position" > (0)::numeric))
);


--
-- Name: TABLE path_item; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.path_item IS 'One Story''s place on one Path. `position` is the owner''s judgement, spaced so that a re-order writes one row; there is deliberately no column an order could be derived from.';


--
-- Name: COLUMN path_item."position"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.path_item."position" IS 'Sparse and numeric: a move is the midpoint of the two new neighbours.';


--
-- Name: person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.person (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT person_name_is_not_blank CHECK (((name = btrim(name)) AND (name <> ''::text)))
);


--
-- Name: TABLE person; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.person IS 'Someone credited on a Story. Named once and pointed at from many Credits, so that "everything read by Jeph Loeb" is a join rather than a string comparison.';


--
-- Name: provenance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provenance (
    id text NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT provenance_description_is_not_blank CHECK (((description = btrim(description)) AND (description <> ''::text))),
    CONSTRAINT provenance_display_order_is_positive CHECK ((display_order > 0)),
    CONSTRAINT provenance_id_is_a_slug CHECK ((id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text)),
    CONSTRAINT provenance_name_is_not_blank CHECK (((name = btrim(name)) AND (name <> ''::text)))
);


--
-- Name: TABLE provenance; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.provenance IS 'How a record came to be known, and therefore how far it can be trusted. Origin only: the grain of a score is `rating.scale` (ADR-0008). Carried by every Reading and every Rating, and stored as data so that the import can name a new one without a release.';


--
-- Name: rating; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rating (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    story_id uuid NOT NULL,
    reading_id uuid,
    score numeric NOT NULL,
    prose text,
    provenance_id text NOT NULL,
    set_at timestamp with time zone DEFAULT now() NOT NULL,
    scale text NOT NULL,
    CONSTRAINT rating_prose_is_not_blank CHECK (((prose IS NULL) OR (btrim(prose) <> ''::text))),
    CONSTRAINT rating_scale_is_coarse_or_half_points CHECK ((scale = ANY (ARRAY['coarse'::text, 'half-points'::text]))),
    CONSTRAINT rating_score_is_in_half_points CHECK (((score * (2)::numeric) = trunc((score * (2)::numeric)))),
    CONSTRAINT rating_score_is_one_to_ten CHECK (((score >= (1)::numeric) AND (score <= (10)::numeric)))
);


--
-- Name: TABLE rating; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.rating IS 'The owner''s judgement of a Story: 1 to 10 in half points, with prose where they wrote some, the grain it was given in, and where it came from — two separate axes (ADR-0008). It never attaches to a Volume (ADR-0001), and this table has no column with which it could.';


--
-- Name: COLUMN rating.set_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rating.set_at IS 'When the owner last set this judgement. What "the most recent score" is ordered by.';


--
-- Name: COLUMN rating.scale; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.rating.scale IS 'The grain the owner gave this score in: half-points on the model''s 1-10 scale, or coarse for one given out of 5 and doubled onto it. Not a Provenance (ADR-0008).';


--
-- Name: reading; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    story_id uuid NOT NULL,
    medium text NOT NULL,
    outcome text,
    started_on date,
    ended_on date,
    provenance_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    volume_id uuid,
    CONSTRAINT reading_did_not_end_before_it_started CHECK (((started_on IS NULL) OR (ended_on IS NULL) OR (ended_on >= started_on))),
    CONSTRAINT reading_digital_went_through_no_volume CHECK (((volume_id IS NULL) OR (medium = 'paper'::text))),
    CONSTRAINT reading_medium_is_paper_or_digital CHECK ((medium = ANY (ARRAY['paper'::text, 'digital'::text]))),
    CONSTRAINT reading_outcome_is_finished_or_abandoned CHECK (((outcome IS NULL) OR (outcome = ANY (ARRAY['finished'::text, 'abandoned'::text])))),
    CONSTRAINT reading_unconcluded_has_not_ended CHECK (((outcome IS NOT NULL) OR (ended_on IS NULL)))
);


--
-- Name: TABLE reading; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.reading IS 'One act of reading a Story: an event, never a status field. Several for the same Story is the ordinary case, because rereading is.';


--
-- Name: COLUMN reading.outcome; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.reading.outcome IS 'finished or abandoned; null while the Reading is still in progress.';


--
-- Name: COLUMN reading.volume_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.reading.volume_id IS 'The object the reading went through, where there was one. Null is the ordinary case: being read and being owned are unrelated facts.';


--
-- Name: reading_list_pin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_list_pin (
    path_id uuid,
    series_id uuid,
    pinned_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT reading_list_pin_has_one_subject CHECK (((path_id IS NULL) <> (series_id IS NULL)))
);


--
-- Name: TABLE reading_list_pin; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.reading_list_pin IS 'The only thing the Reading list stores. The list itself composes itself from active Paths and Series being collected and is a table nowhere; a pin is the owner''s disagreement with its order, and points at the source of an entry — a Path or a Series — because an entry has no stable row of its own.';


--
-- Name: COLUMN reading_list_pin.pinned_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.reading_list_pin.pinned_at IS 'The most recently pinned comes first: pinning is the act of saying "this next".';


--
-- Name: series; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.series (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    publisher text NOT NULL,
    edition_line text,
    published_count integer NOT NULL,
    status text NOT NULL,
    collecting_since date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT series_edition_line_is_not_blank CHECK (((edition_line IS NULL) OR ((edition_line = btrim(edition_line)) AND (edition_line <> ''::text)))),
    CONSTRAINT series_name_is_not_blank CHECK (((name = btrim(name)) AND (name <> ''::text))),
    CONSTRAINT series_published_count_is_not_negative CHECK ((published_count >= 0)),
    CONSTRAINT series_publisher_is_not_blank CHECK (((publisher = btrim(publisher)) AND (publisher <> ''::text))),
    CONSTRAINT series_status_is_ongoing_or_concluded CHECK ((status = ANY (ARRAY['ongoing'::text, 'concluded'::text])))
);


--
-- Name: TABLE series; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.series IS 'A publisher''s ordered sequence of Volumes for one edition, held as a completeness ledger: how many Volumes are out, whether the Series is ongoing, and whether the owner decided to complete it. What is missing is derived from those and the shelf, and stored nowhere.';


--
-- Name: COLUMN series.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.series.name IS 'The Series name without its edition: Death Note.';


--
-- Name: COLUMN series.edition_line; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.series.edition_line IS 'The publisher''s edition, not the Series itself.';


--
-- Name: COLUMN series.published_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.series.published_count IS 'How many Volumes are out. The owner''s knowledge, and it grows.';


--
-- Name: COLUMN series.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.series.status IS 'ongoing or concluded.';


--
-- Name: COLUMN series.collecting_since; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.series.collecting_since IS 'The day the owner decided to complete this Series. Null is a Series they are not collecting, and owning Volumes of it never fills this in.';


--
-- Name: story; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.story (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    type_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT story_title_is_not_blank CHECK (((title = btrim(title)) AND (title <> ''::text)))
);


--
-- Name: TABLE story; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.story IS 'The narrative unit the owner reads and forms an opinion about. Reachable with no Volume at all, and never reached *through* one (ADR-0001).';


--
-- Name: type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.type (
    id text NOT NULL,
    name text NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT type_display_order_is_positive CHECK ((display_order > 0)),
    CONSTRAINT type_id_is_a_slug CHECK ((id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text)),
    CONSTRAINT type_name_is_not_blank CHECK (((name = btrim(name)) AND (name <> ''::text)))
);


--
-- Name: TABLE type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.type IS 'An attribute of a Story, never a kind of thing: a novel and a tankobon differ in their attributes and never in their shape (ADR-0006). Stored as data so that a new Type is an insert rather than a deployment.';


--
-- Name: COLUMN type.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.type.id IS 'Stable slug, and what MCP shows an external reader.';


--
-- Name: COLUMN type.name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.type.name IS 'What the owner reads on screen.';


--
-- Name: COLUMN type.display_order; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.type.display_order IS 'The order the five are offered in.';


--
-- Name: volume; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.volume (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    publisher text NOT NULL,
    edition_line text,
    binding_id text NOT NULL,
    language text NOT NULL,
    isbn text,
    series_id uuid,
    series_number integer,
    CONSTRAINT volume_edition_line_is_not_blank CHECK (((edition_line IS NULL) OR ((edition_line = btrim(edition_line)) AND (edition_line <> ''::text)))),
    CONSTRAINT volume_in_a_series_has_a_number CHECK (((series_id IS NULL) = (series_number IS NULL))),
    CONSTRAINT volume_isbn_is_ten_or_thirteen_characters CHECK (((isbn IS NULL) OR (isbn ~ '^[0-9]{9}[0-9Xx]$|^[0-9]{13}$'::text))),
    CONSTRAINT volume_language_is_a_code CHECK ((language ~ '^[a-z]{2,3}(-[a-z0-9]+)*$'::text)),
    CONSTRAINT volume_publisher_is_not_blank CHECK (((publisher = btrim(publisher)) AND (publisher <> ''::text))),
    CONSTRAINT volume_series_number_is_positive CHECK (((series_number IS NULL) OR (series_number > 0))),
    CONSTRAINT volume_title_is_not_blank CHECK (((title = btrim(title)) AND (title <> ''::text)))
);


--
-- Name: TABLE volume; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.volume IS 'One object as catalogued: publisher, edition line, Binding, language, ISBN — everything about the *thing* and nothing about the narrative. Being catalogued is not being owned (ADR-0007): whether it is in the house is an acquisition. There is deliberately no medium column, so an owned ebook is not a row this table can hold.';


--
-- Name: COLUMN volume.edition_line; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.volume.edition_line IS 'The publisher''s line, not the volume itself.';


--
-- Name: COLUMN volume.language; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.volume.language IS 'A language code — it, en, ja.';


--
-- Name: COLUMN volume.series_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.volume.series_id IS 'The Series this object belongs to, where it belongs to one.';


--
-- Name: COLUMN volume.series_number; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.volume.series_number IS 'Its position in that Series: 12 of Slam Dunk.';


--
-- Name: volume_story; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.volume_story (
    volume_id uuid NOT NULL,
    story_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE volume_story; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.volume_story IS 'Which Stories a Volume carries: many-to-many in both directions (ADR-0001). One Volume holds several Stories and one Story spans several Volumes, and neither side is derived from the other — the link is stored.';


--
-- Name: wish; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wish (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    volume_id uuid NOT NULL,
    priority integer NOT NULL,
    target_price numeric(10,2),
    price_found numeric(10,2),
    shop text,
    opened_on date DEFAULT CURRENT_DATE NOT NULL,
    closed_on date,
    CONSTRAINT wish_close_follows_open CHECK (((closed_on IS NULL) OR (closed_on >= opened_on))),
    CONSTRAINT wish_price_found_is_not_negative CHECK (((price_found IS NULL) OR (price_found >= (0)::numeric))),
    CONSTRAINT wish_priority_is_one_to_three CHECK (((priority >= 1) AND (priority <= 3))),
    CONSTRAINT wish_shop_is_not_blank CHECK (((shop IS NULL) OR ((shop = btrim(shop)) AND (shop <> ''::text)))),
    CONSTRAINT wish_target_price_is_not_negative CHECK (((target_price IS NULL) OR (target_price >= (0)::numeric)))
);


--
-- Name: TABLE wish; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.wish IS 'An open intention to acquire a named Volume. There is deliberately no state column: a fulfilled Wish is a Wish that ended, so the end is a day and `Acquistato` is not representable. Nothing but the close verb writes closed_on.';


--
-- Name: COLUMN wish.priority; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.wish.priority IS 'Which to buy first: 1 next, 2 soon, 3 someday.';


--
-- Name: COLUMN wish.closed_on; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.wish.closed_on IS 'Null is an open Wish, and the shopping list. A day is a Wish the owner ended.';


--
-- Name: acquisition acquisition_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition
    ADD CONSTRAINT acquisition_pkey PRIMARY KEY (id);


--
-- Name: binding binding_display_order_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.binding
    ADD CONSTRAINT binding_display_order_key UNIQUE (display_order);


--
-- Name: binding binding_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.binding
    ADD CONSTRAINT binding_name_key UNIQUE (name);


--
-- Name: binding binding_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.binding
    ADD CONSTRAINT binding_pkey PRIMARY KEY (id);


--
-- Name: credit credit_is_one_role_per_person_per_story; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit
    ADD CONSTRAINT credit_is_one_role_per_person_per_story UNIQUE (story_id, person_id, role_id);


--
-- Name: credit credit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit
    ADD CONSTRAINT credit_pkey PRIMARY KEY (id);


--
-- Name: credit_role credit_role_display_order_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_role
    ADD CONSTRAINT credit_role_display_order_key UNIQUE (display_order);


--
-- Name: credit_role credit_role_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_role
    ADD CONSTRAINT credit_role_name_key UNIQUE (name);


--
-- Name: credit_role credit_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_role
    ADD CONSTRAINT credit_role_pkey PRIMARY KEY (id);


--
-- Name: declared_constraint declared_constraint_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.declared_constraint
    ADD CONSTRAINT declared_constraint_pkey PRIMARY KEY (id);


--
-- Name: edition_note edition_note_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edition_note
    ADD CONSTRAINT edition_note_pkey PRIMARY KEY (volume_id);


--
-- Name: inbox_entry inbox_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inbox_entry
    ADD CONSTRAINT inbox_entry_pkey PRIMARY KEY (id);


--
-- Name: path_item path_item_is_one_stop; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.path_item
    ADD CONSTRAINT path_item_is_one_stop PRIMARY KEY (path_id, story_id);


--
-- Name: path_item path_item_position_is_one_place; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.path_item
    ADD CONSTRAINT path_item_position_is_one_place UNIQUE (path_id, "position");


--
-- Name: path path_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.path
    ADD CONSTRAINT path_pkey PRIMARY KEY (id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: provenance provenance_display_order_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provenance
    ADD CONSTRAINT provenance_display_order_key UNIQUE (display_order);


--
-- Name: provenance provenance_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provenance
    ADD CONSTRAINT provenance_name_key UNIQUE (name);


--
-- Name: provenance provenance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provenance
    ADD CONSTRAINT provenance_pkey PRIMARY KEY (id);


--
-- Name: rating rating_is_one_per_story_and_reading; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT rating_is_one_per_story_and_reading UNIQUE NULLS NOT DISTINCT (story_id, reading_id);


--
-- Name: rating rating_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT rating_pkey PRIMARY KEY (id);


--
-- Name: reading reading_id_and_story; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading
    ADD CONSTRAINT reading_id_and_story UNIQUE (id, story_id);


--
-- Name: reading reading_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading
    ADD CONSTRAINT reading_pkey PRIMARY KEY (id);


--
-- Name: series series_is_one_per_edition_line; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_is_one_per_edition_line UNIQUE NULLS NOT DISTINCT (name, publisher, edition_line);


--
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- Name: story story_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.story
    ADD CONSTRAINT story_pkey PRIMARY KEY (id);


--
-- Name: type type_display_order_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type
    ADD CONSTRAINT type_display_order_key UNIQUE (display_order);


--
-- Name: type type_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type
    ADD CONSTRAINT type_name_key UNIQUE (name);


--
-- Name: type type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type
    ADD CONSTRAINT type_pkey PRIMARY KEY (id);


--
-- Name: volume volume_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.volume
    ADD CONSTRAINT volume_pkey PRIMARY KEY (id);


--
-- Name: volume_story volume_story_is_said_once; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.volume_story
    ADD CONSTRAINT volume_story_is_said_once PRIMARY KEY (volume_id, story_id);


--
-- Name: wish wish_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish
    ADD CONSTRAINT wish_pkey PRIMARY KEY (id);


--
-- Name: acquisition_by_volume; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX acquisition_by_volume ON public.acquisition USING btree (volume_id, released_on);


--
-- Name: acquisition_one_open_per_volume; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX acquisition_one_open_per_volume ON public.acquisition USING btree (volume_id) WHERE (released_on IS NULL);


--
-- Name: credit_by_person; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX credit_by_person ON public.credit USING btree (person_id);


--
-- Name: credit_by_story; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX credit_by_story ON public.credit USING btree (story_id);


--
-- Name: declared_constraint_by_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX declared_constraint_by_path ON public.declared_constraint USING btree (path_id, declared_at);


--
-- Name: path_item_in_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX path_item_in_order ON public.path_item USING btree (path_id, "position");


--
-- Name: path_name_names_one_route; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX path_name_names_one_route ON public.path USING btree (lower(name));


--
-- Name: person_is_named_once; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX person_is_named_once ON public.person USING btree (lower(name));


--
-- Name: rating_by_story; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rating_by_story ON public.rating USING btree (story_id, set_at DESC);


--
-- Name: reading_by_story; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reading_by_story ON public.reading USING btree (story_id, started_on DESC NULLS LAST);


--
-- Name: reading_list_pin_one_per_path; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX reading_list_pin_one_per_path ON public.reading_list_pin USING btree (path_id) WHERE (path_id IS NOT NULL);


--
-- Name: reading_list_pin_one_per_series; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX reading_list_pin_one_per_series ON public.reading_list_pin USING btree (series_id) WHERE (series_id IS NOT NULL);


--
-- Name: story_by_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX story_by_type ON public.story USING btree (type_id);


--
-- Name: volume_story_by_story; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX volume_story_by_story ON public.volume_story USING btree (story_id);


--
-- Name: wish_one_open_per_volume; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX wish_one_open_per_volume ON public.wish USING btree (volume_id) WHERE (closed_on IS NULL);


--
-- Name: acquisition volume_holds_one_position_when_acquired; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER volume_holds_one_position_when_acquired AFTER INSERT OR UPDATE OF released_on ON public.acquisition FOR EACH ROW EXECUTE FUNCTION public.volume_holds_one_position();


--
-- Name: volume volume_holds_one_position_when_placed; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER volume_holds_one_position_when_placed AFTER INSERT OR UPDATE OF series_id, series_number ON public.volume FOR EACH ROW EXECUTE FUNCTION public.volume_holds_one_position();


--
-- Name: acquisition acquisition_volume_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acquisition
    ADD CONSTRAINT acquisition_volume_exists FOREIGN KEY (volume_id) REFERENCES public.volume(id);


--
-- Name: credit credit_person_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit
    ADD CONSTRAINT credit_person_exists FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: credit credit_role_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit
    ADD CONSTRAINT credit_role_exists FOREIGN KEY (role_id) REFERENCES public.credit_role(id);


--
-- Name: credit credit_story_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit
    ADD CONSTRAINT credit_story_exists FOREIGN KEY (story_id) REFERENCES public.story(id) ON DELETE CASCADE;


--
-- Name: declared_constraint declared_constraint_path_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.declared_constraint
    ADD CONSTRAINT declared_constraint_path_exists FOREIGN KEY (path_id) REFERENCES public.path(id) ON DELETE CASCADE;


--
-- Name: edition_note edition_note_volume_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edition_note
    ADD CONSTRAINT edition_note_volume_exists FOREIGN KEY (volume_id) REFERENCES public.volume(id) ON DELETE CASCADE;


--
-- Name: path_item path_item_path_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.path_item
    ADD CONSTRAINT path_item_path_exists FOREIGN KEY (path_id) REFERENCES public.path(id) ON DELETE CASCADE;


--
-- Name: path_item path_item_story_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.path_item
    ADD CONSTRAINT path_item_story_exists FOREIGN KEY (story_id) REFERENCES public.story(id) ON DELETE CASCADE;


--
-- Name: rating rating_belongs_to_the_read_story; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT rating_belongs_to_the_read_story FOREIGN KEY (reading_id, story_id) REFERENCES public.reading(id, story_id) ON DELETE SET NULL (reading_id);


--
-- Name: rating rating_provenance_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT rating_provenance_exists FOREIGN KEY (provenance_id) REFERENCES public.provenance(id);


--
-- Name: rating rating_story_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT rating_story_exists FOREIGN KEY (story_id) REFERENCES public.story(id) ON DELETE CASCADE;


--
-- Name: reading_list_pin reading_list_pin_path_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_list_pin
    ADD CONSTRAINT reading_list_pin_path_exists FOREIGN KEY (path_id) REFERENCES public.path(id) ON DELETE CASCADE;


--
-- Name: reading_list_pin reading_list_pin_series_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_list_pin
    ADD CONSTRAINT reading_list_pin_series_exists FOREIGN KEY (series_id) REFERENCES public.series(id) ON DELETE CASCADE;


--
-- Name: reading reading_provenance_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading
    ADD CONSTRAINT reading_provenance_exists FOREIGN KEY (provenance_id) REFERENCES public.provenance(id);


--
-- Name: reading reading_story_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading
    ADD CONSTRAINT reading_story_exists FOREIGN KEY (story_id) REFERENCES public.story(id) ON DELETE CASCADE;


--
-- Name: reading reading_volume_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading
    ADD CONSTRAINT reading_volume_exists FOREIGN KEY (volume_id) REFERENCES public.volume(id) ON DELETE SET NULL;


--
-- Name: story story_type_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.story
    ADD CONSTRAINT story_type_exists FOREIGN KEY (type_id) REFERENCES public.type(id);


--
-- Name: volume volume_binding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.volume
    ADD CONSTRAINT volume_binding_id_fkey FOREIGN KEY (binding_id) REFERENCES public.binding(id);


--
-- Name: volume volume_series_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.volume
    ADD CONSTRAINT volume_series_exists FOREIGN KEY (series_id) REFERENCES public.series(id);


--
-- Name: volume_story volume_story_story_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.volume_story
    ADD CONSTRAINT volume_story_story_exists FOREIGN KEY (story_id) REFERENCES public.story(id) ON DELETE CASCADE;


--
-- Name: volume_story volume_story_volume_exists; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.volume_story
    ADD CONSTRAINT volume_story_volume_exists FOREIGN KEY (volume_id) REFERENCES public.volume(id) ON DELETE CASCADE;


--
-- Name: wish wish_volume_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish
    ADD CONSTRAINT wish_volume_id_fkey FOREIGN KEY (volume_id) REFERENCES public.volume(id);


--
-- PostgreSQL database dump complete
--
