-- The Inbox learns to carry an Amendment (ADR-0011).
--
-- An entry was a creation and nothing else: `proposes` named one of the three entities, and
-- `created_id` held the row an approval made. An Amendment is about a record that **already
-- exists**, so two things were missing and one was false.
--
--   act         which of the two an entry is. Everything that predates this file is a
--               creation, which is what the default says.
--   subject_id  the record an amendment is about. Polymorphic, like `created_id`, and for
--               the same reason: which table it is in is `proposes`, and a foreign key
--               would have to name one table.
--
-- And the false one: `inbox_entry_approval_names_what_it_created` asserted that an approved
-- entry created something, which an approved amendment does not. It is split in two — an
-- approved creation names what it created, an amendment names what it changes — so that
-- neither branch can be violated in either direction.
--
-- Generated by `drizzle-kit generate` and then hand-finished: the `comment on` statements
-- below are the part Drizzle does not write, and they are where this schema documents
-- itself (ADR-0009).

ALTER TABLE "inbox_entry" DROP CONSTRAINT "inbox_entry_approval_names_what_it_created";--> statement-breakpoint
ALTER TABLE "inbox_entry" ADD COLUMN "act" text DEFAULT 'create' NOT NULL;--> statement-breakpoint
ALTER TABLE "inbox_entry" ADD COLUMN "subject_id" uuid;--> statement-breakpoint
ALTER TABLE "inbox_entry" ADD CONSTRAINT "inbox_entry_act_is_create_or_amend" CHECK (act = ANY (ARRAY['create'::text, 'amend'::text]));--> statement-breakpoint
ALTER TABLE "inbox_entry" ADD CONSTRAINT "inbox_entry_an_amendment_names_what_it_amends" CHECK ((subject_id IS NOT NULL) = (act = 'amend'::text));--> statement-breakpoint
ALTER TABLE "inbox_entry" ADD CONSTRAINT "inbox_entry_approved_creation_names_what_it_created" CHECK ((created_id IS NOT NULL) = ((act = 'create'::text) AND (NOT (outcome IS DISTINCT FROM 'approved'::text))));--> statement-breakpoint

COMMENT ON TABLE public.inbox_entry IS 'What an external assistant asked for and the owner has not decided yet (ADR-0005, ADR-0011). Creating a Story, Volume or Series over MCP is impossible, and so is completing or correcting one; the attempt lands here as a proposal, and approval is the act that creates the entity or changes the record. A rejected entry leaves no trace in the domain, because this row is the only trace a proposal ever had.';--> statement-breakpoint

COMMENT ON COLUMN public.inbox_entry.act IS 'create or amend. A creation makes a record that does not exist yet; an amendment completes or corrects one that does, and names it in subject_id (ADR-0011).';--> statement-breakpoint

COMMENT ON COLUMN public.inbox_entry.proposes IS 'story, volume or series - the three ADR-0005 allows to be proposed, and the kind of record an amendment is about: an ISBN amendment is a volume, a published-count amendment a series. Not called type: Type is an attribute of a Story and lives in details.';--> statement-breakpoint

COMMENT ON COLUMN public.inbox_entry.reference IS 'The title or reference as given. On an amendment it is the record''s own title, read off it when the amendment was proposed, so an entry names what it is about without a join.';--> statement-breakpoint

COMMENT ON COLUMN public.inbox_entry.details IS 'Everything else the assistant supplied, untrusted and unchecked. On a creation it becomes a verb''s arguments at approval and meets that verb''s constraints there; on an amendment it is the fields proposed, and only those, so what it does not name is left standing.';--> statement-breakpoint

COMMENT ON COLUMN public.inbox_entry.subject_id IS 'The record an amendment is about, in the table proposes names. Null on a creation, which has no record yet. No foreign key: which table it points at is data, and a key would have to choose one.';--> statement-breakpoint

COMMENT ON COLUMN public.inbox_entry.created_id IS 'The story, volume or series the approval created. Null on a rejected or waiting entry, and null on an amendment, which changes a record rather than making one.'
