-- A Volume carries its cover as a **reference**, never as bytes (ADR-0013, #32).
--
-- Google Books is the only source that has these covers — 91% of a 54-ISBN sample of real
-- Italian comics, against 5.6% for Open Library and 5.6% for Italy's own legal deposit
-- catalogue (`docs/research/cover-images-by-isbn.md`) — and its terms forbid keeping them:
-- the image arrives with `cache-control: private, max-age=86400` and the Google APIs ToS
-- §5.e.1 bars "permanent copies ... or cached copies longer than permitted by the cache
-- header". So what lands on the row is what the *record* says, and the bytes stay where
-- they are:
--
--   cover_source        which source answered: google-books, or open-library
--   cover_reference     that source's own id for the record - Google's volume id, which is
--                       what makes a second lookup unnecessary for the life of the row
--   cover_url           what an <img src> points at. On the source's own domain, always
--   cover_info_url      the source's page for this book, which is the per-book link a
--                       public page owes Google under its branding guidelines
--   cover_looked_up_at  when a lookup last ran over this object. It is how "we asked and
--                       there is none" is told apart from "nobody has ever asked"
--   own_image_url       the owner's own photograph or scan, hosted in our own bucket,
--                       which overrides the looked-up one. The only image this application
--                       is allowed to keep, and the only thing that will ever cover a
--                       Bonelli monthly - those carry an ISSN-derived periodical EAN and no
--                       ISBN at all, so nothing keyed by ISBN will ever find them
--
-- **The prohibition is a constraint rather than a habit.** `cover_url` must be on the
-- source's own domain, so an `insert` of a URL pointing into our own storage is refused by
-- Postgres rather than by somebody remembering ADR-0013 during review; and `own_image_url`
-- must *not* be on either of theirs, so the escape hatch cannot quietly become a second
-- place a third party's bytes are claimed as the owner's.
--
-- Generated by `drizzle-kit generate` and then hand-finished: the `comment on` statements
-- below are the part Drizzle does not write, and they are where this schema documents
-- itself (ADR-0009).

ALTER TABLE "volume" ADD COLUMN "cover_source" text;--> statement-breakpoint
ALTER TABLE "volume" ADD COLUMN "cover_reference" text;--> statement-breakpoint
ALTER TABLE "volume" ADD COLUMN "cover_url" text;--> statement-breakpoint
ALTER TABLE "volume" ADD COLUMN "cover_info_url" text;--> statement-breakpoint
ALTER TABLE "volume" ADD COLUMN "cover_looked_up_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "volume" ADD COLUMN "own_image_url" text;--> statement-breakpoint
ALTER TABLE "volume" ADD CONSTRAINT "volume_cover_is_a_source_and_a_url_together" CHECK ((cover_source IS NULL) = (cover_url IS NULL));--> statement-breakpoint
ALTER TABLE "volume" ADD CONSTRAINT "volume_cover_source_is_one_this_app_looks_up" CHECK ((cover_source IS NULL) OR (cover_source = ANY (ARRAY['google-books'::text, 'open-library'::text])));--> statement-breakpoint
ALTER TABLE "volume" ADD CONSTRAINT "volume_cover_is_hotlinked_and_never_hosted" CHECK ((cover_url IS NULL) OR (cover_url ~ '^https://((bks[0-9]+\.)?books\.google\.com|covers\.openlibrary\.org)/'::text));--> statement-breakpoint
ALTER TABLE "volume" ADD CONSTRAINT "volume_cover_was_looked_up" CHECK ((cover_url IS NULL) OR (cover_looked_up_at IS NOT NULL));--> statement-breakpoint
ALTER TABLE "volume" ADD CONSTRAINT "volume_cover_reference_and_link_come_with_a_cover" CHECK ((cover_url IS NOT NULL) OR ((cover_reference IS NULL) AND (cover_info_url IS NULL)));--> statement-breakpoint
ALTER TABLE "volume" ADD CONSTRAINT "volume_own_image_is_the_owners_own" CHECK ((own_image_url IS NULL) OR ((own_image_url ~ '^https://[^ ]+$'::text) AND (own_image_url !~ '^https://((bks[0-9]+\.)?books\.google\.com|covers\.openlibrary\.org)/'::text)));--> statement-breakpoint

COMMENT ON COLUMN public.volume.cover_source IS 'Which source the cover reference came from: google-books or open-library. Null where no lookup has found one - see cover_looked_up_at for whether one was ever asked (ADR-0013).';--> statement-breakpoint

COMMENT ON COLUMN public.volume.cover_reference IS 'The source''s own id for this record - Google Books'' volume id. A fact about the record rather than a copy of the content, and what lets a second render skip the ISBN hop entirely.';--> statement-breakpoint

COMMENT ON COLUMN public.volume.cover_url IS 'What an <img src> points at, on the source''s own domain: the cover is hotlinked and never hosted (ADR-0013). Google''s is 128px wide and that is the only size that exists - every larger zoom returns a byte-identical "image not available" placeholder.';--> statement-breakpoint

COMMENT ON COLUMN public.volume.cover_info_url IS 'The source''s own page for this book. Google Books requires a prominent per-book link to it on a public page, and the same response that carries the thumbnail carries this.';--> statement-breakpoint

COMMENT ON COLUMN public.volume.cover_looked_up_at IS 'When a lookup last ran over this object. Set whether one was found or not, which is what makes an absence a recorded answer rather than a question nobody asked, and what orders the lazy re-check of a cover that has gone missing.';--> statement-breakpoint

COMMENT ON COLUMN public.volume.own_image_url IS 'The owner''s own photograph or scan, hosted in our own bucket, which overrides the looked-up cover. The one image this application may keep: it is the owner''s, no third party''s terms reach it, and it is the only thing that will ever cover a Bonelli monthly, which has no ISBN to look up.'
