-- A **Want** is an open intention to read a Story, standing on its own (#35, #34).
--
-- It is the fact the library was missing. It could already say *I read this* (a Reading), *I
-- want to own this object* (a Wish), *I mean to complete this line* (a Series being collected)
-- and *I mean to read these in this order* (a Path) — and had no way at all to say *I want to
-- read this*. So the only door into the Reading list was minting a Path: a named, ordered
-- route, uniquely indexed and unable to be undefined, for something that was never a route.
--
-- Three columns, and the interesting thing is the two that are **not** here:
--
--   * **there is no `closed_on`.** A Want ends by itself and never by a deliberate act, which
--     is exactly where it parts from the Wish beside it. It falls quiet when a **Reading began
--     after the Want was opened** — a comparison of dates rather than a state, derived on the
--     way out in `src/core/queries/want.ts` and stored nowhere. That is what makes rereading
--     ordinary instead of a special case: a Want opened today on a Story read in 2019 finds no
--     Reading later than itself and stands on the list until the owner actually rereads it, and
--     nothing anywhere has to say *this one is a reread*;
--   * **there is no priority, no name and no order.** A Want is one sentence about one Story.
--     Where it sits on the Reading list is the Reading list's business, and the only order the
--     owner keeps by hand is the pin.
--
-- `opened_at` is a timestamp rather than a date because the comparison above is against the
-- moment a Reading was recorded, and two acts on one evening are routine — the owner says *I
-- want to read this* and then, having found it on the shelf, *I have started it*.
--
-- **One Want per Story, and Postgres is what says so** rather than a read-then-insert in the
-- verb. Cascading on the Story, because a Want is an intention *about* a narrative and a
-- narrative that was struck from the library has no intention left to hold (ADR-0015).
--
-- Generated by `drizzle-kit generate` and then hand-finished: the `comment on` statements are
-- the part Drizzle does not write, and they are where this schema documents itself (ADR-0009).

CREATE TABLE "want" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "want_one_open_per_story" UNIQUE("story_id")
);
--> statement-breakpoint
ALTER TABLE "want" ADD CONSTRAINT "want_story_exists" FOREIGN KEY ("story_id") REFERENCES "public"."story"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "want_newest_first" ON "want" USING btree ("opened_at" DESC NULLS LAST);--> statement-breakpoint

COMMENT ON TABLE public.want IS 'An open intention to read a Story, belonging to no Path. It pairs with the Wish and the pair is the whole distinction: a Wish names a Volume and is about owning, a Want names a Story and is about reading. Neither implies the other.';--> statement-breakpoint

COMMENT ON COLUMN public.want.story_id IS 'The narrative the owner means to read. One Want per Story, enforced here rather than by an if in the verb; a Story struck from the library takes its Want with it.';--> statement-breakpoint

COMMENT ON COLUMN public.want.opened_at IS 'When the owner said it. There is no closing column: a Want falls quiet when a Reading began after this moment, which is a comparison rather than a state and is what makes a planned reread ordinary.'
