-- A Story says how many Instalments it has, and a pass says how far it got (#37).
--
-- An **Instalment** is one numbered part of a serialized Story — *Ultimate Spider-Man*
-- #1…#160, *Slam Dunk*'s twenty — and it belongs to the **narrative and never to a
-- printing**. That is the whole of its usefulness: *thirty-five of a hundred and sixty*
-- stays true however the owner read them, in singles, in an omnibus or half in each, where
-- *one of three omnibus* is a fact about a shelf and says nothing about the work.
--
-- Four columns, and every one of them is nullable because **Instalments are optional and
-- cost nothing where they are not wanted**:
--
--   story.instalments          how many parts the work has. Null is *not serialized*, which
--                              is the ordinary case: a one-shot is asked nothing
--   volume_story.covers_from   the range of the work this object collects, written by hand
--   volume_story.covers_to     only where one object collects many — the omnibus, and very
--                              nearly nothing else. Null means the range **follows the
--                              Volume's position in its Series**, so volume 7 is instalment
--                              7 and nobody types anything
--   reading.at_instalment      the last Instalment this pass finished. It is on the pass
--                              rather than on the Story on purpose: how far you are is a
--                              fact about an **event**, which is what keeps the glossary's
--                              ban on a progress field honest, and what makes reading half
--                              a run in singles and half in a deluxe one number
--
-- **The invariants that cross two tables are triggers rather than `if`s in the verbs**, for
-- the reason every other invariant here is a constraint: the database refuses what must
-- never be true rather than trusting a caller to remember. A check constraint cannot read
-- another table, so the two that must — an Instalment inside the work, and a work that
-- still holds what has been read of it — are functions raising with a constraint name, the
-- shape `volume_holds_one_position()` established in 0000. The verbs turn that name into
-- the prose the owner reads (`src/core/refusal.ts`), so nothing above the core sees a
-- SQLSTATE.
--
-- Generated by `drizzle-kit generate` and then hand-finished: the two functions, their
-- three triggers and every `comment on` below are the part Drizzle does not write
-- (ADR-0009).

ALTER TABLE "reading" ADD COLUMN "at_instalment" integer;--> statement-breakpoint
ALTER TABLE "story" ADD COLUMN "instalments" integer;--> statement-breakpoint
ALTER TABLE "volume_story" ADD COLUMN "covers_from" integer;--> statement-breakpoint
ALTER TABLE "volume_story" ADD COLUMN "covers_to" integer;--> statement-breakpoint
ALTER TABLE "reading" ADD CONSTRAINT "reading_at_instalment_is_positive" CHECK ((at_instalment IS NULL) OR (at_instalment > 0));--> statement-breakpoint
ALTER TABLE "story" ADD CONSTRAINT "story_instalments_are_positive" CHECK ((instalments IS NULL) OR (instalments > 0));--> statement-breakpoint
ALTER TABLE "volume_story" ADD CONSTRAINT "volume_story_covers_a_whole_range" CHECK ((covers_from IS NULL) = (covers_to IS NULL));--> statement-breakpoint
ALTER TABLE "volume_story" ADD CONSTRAINT "volume_story_cover_does_not_invert" CHECK ((covers_from IS NULL) OR (covers_to >= covers_from));--> statement-breakpoint
ALTER TABLE "volume_story" ADD CONSTRAINT "volume_story_cover_starts_at_one" CHECK ((covers_from IS NULL) OR (covers_from > 0));--> statement-breakpoint

CREATE FUNCTION public.an_instalment_lies_inside_the_work() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
  declared integer;
  reached  integer;
  covered  integer;
begin
  select s.instalments into declared from story s where s.id = new.story_id;

  -- Two branches rather than one expression, because PL/pgSQL resolves the fields of `new`
  -- against whichever row type fired the trigger: `new.covers_to` written beside
  -- `new.at_instalment` fails on the `reading` trigger even where it is never reached. The
  -- same reason 0000 splits `volume_holds_one_position()`.
  if tg_table_name = 'reading' then
    reached := new.at_instalment;

    -- Nothing said about how far it got, which is the ordinary pass.
    if reached is null then
      return null;
    end if;

    if declared is null then
      raise exception 'that Story has no Instalments to be at'
        using errcode = 'check_violation',
              constraint = 'reading_at_instalment_needs_a_serialized_story';
    end if;

    if reached > declared then
      raise exception 'that pass got further than the work goes'
        using errcode = 'check_violation',
              constraint = 'reading_at_instalment_is_within_the_work';
    end if;
  else
    covered := new.covers_to;

    -- No range written by hand, so the range follows the object's position in its line.
    if covered is null then
      return null;
    end if;

    if declared is null then
      raise exception 'that Story has no Instalments to cover'
        using errcode = 'check_violation',
              constraint = 'volume_story_cover_needs_a_serialized_story';
    end if;

    if covered > declared then
      raise exception 'that object covers past the end of the work'
        using errcode = 'check_violation',
              constraint = 'volume_story_cover_lies_inside_the_work';
    end if;
  end if;

  return null;
end;
$$;--> statement-breakpoint

COMMENT ON FUNCTION public.an_instalment_lies_inside_the_work() IS 'An Instalment a pass reached, and a range an object covers, both lie inside the Story they are about (#37). A check constraint cannot read another table, so this is the constraint restated across two of them.';--> statement-breakpoint

CREATE TRIGGER reading_at_instalment_lies_inside_the_work
    AFTER INSERT OR UPDATE OF at_instalment, story_id ON public.reading
    FOR EACH ROW EXECUTE FUNCTION public.an_instalment_lies_inside_the_work();--> statement-breakpoint

CREATE TRIGGER volume_story_cover_lies_inside_the_work
    AFTER INSERT OR UPDATE OF covers_from, covers_to, story_id ON public.volume_story
    FOR EACH ROW EXECUTE FUNCTION public.an_instalment_lies_inside_the_work();--> statement-breakpoint

CREATE FUNCTION public.the_work_still_holds_what_was_read() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  if new.instalments is not distinct from old.instalments then
    return null;
  end if;

  -- Shortening a work, or taking its numbering away altogether, is refused while a pass or
  -- an object stands beyond the new end. Otherwise the invariant above would hold only at
  -- the moment it was written, and *seven of five* would be reachable by editing the five.
  if exists (
    select 1 from reading r
     where r.story_id = new.id
       and r.at_instalment is not null
       and (new.instalments is null or r.at_instalment > new.instalments)
  ) then
    raise exception 'a pass through it got further than that'
      using errcode = 'check_violation',
            constraint = 'story_instalments_still_hold_what_was_read';
  end if;

  if exists (
    select 1 from volume_story vs
     where vs.story_id = new.id
       and vs.covers_to is not null
       and (new.instalments is null or vs.covers_to > new.instalments)
  ) then
    raise exception 'an object covers further than that'
      using errcode = 'check_violation',
            constraint = 'story_instalments_still_hold_what_is_covered';
  end if;

  return null;
end;
$$;--> statement-breakpoint

COMMENT ON FUNCTION public.the_work_still_holds_what_was_read() IS 'A Story cannot be shortened past what a pass has read of it or what an object covers of it (#37) - otherwise "seven of five" is reachable by editing the five.';--> statement-breakpoint

CREATE TRIGGER story_instalments_still_hold_what_was_read
    AFTER UPDATE OF instalments ON public.story
    FOR EACH ROW EXECUTE FUNCTION public.the_work_still_holds_what_was_read();--> statement-breakpoint

COMMENT ON COLUMN public.story.instalments IS 'How many Instalments this Story has, where it was serialized: Slam Dunk''s twenty. Null is not serialized at all, which is the ordinary case - a one-shot is never asked (#37). It belongs to the narrative and never to a printing, so it is true however the owner read them.';--> statement-breakpoint

COMMENT ON COLUMN public.volume_story.covers_from IS 'The first Instalment of the Story this object collects. Null means the range follows the Volume''s position in its Series, which is every manga on these shelves: volume 7 is instalment 7 and nobody types anything (#37).';--> statement-breakpoint

COMMENT ON COLUMN public.volume_story.covers_to IS 'The last Instalment of the Story this object collects - an omnibus covering one to thirty-five. Written by hand only where one object collects many; null with covers_from, and then the range follows the Volume''s position in its line (#37).';--> statement-breakpoint

COMMENT ON COLUMN public.reading.at_instalment IS 'The last Instalment this pass finished, which is what answers "seven of twenty" without a progress field on the Story (#37). Null on an unstarted or unnumbered pass. It is on the pass because how far you got is a fact about an event, and it survives changing edition halfway.'
