-- A Series says **which Story it publishes**, and that lone arrow is the only thing the
-- Series and the narrative say to each other (CONTEXT.md, #39).
--
-- Until now a Series and a Story could only reach each other through the objects — the
-- Volumes placed in the Series, and the Stories those Volumes carry — which is two hops and
-- says nothing about what the Series is *for*. So a twenty-first tankobon joining *Slam
-- Dunk* had nowhere to attach and minted a twenty-first narrative, and the owner's
-- hand-kept rows drifted: twenty-two Volumes against twenty-one Stories.
--
-- **Many Series to one Story**, so the column carries no unique index: *Fullmetal Alchemist*
-- is one Story whether it is printed as the standard edition or as the Ultimate Deluxe
-- Edition, and the two Series are two completeness ledgers over one narrative. What is
-- missing is per Series; what it was worth belongs to the Story.
--
-- **Nullable, because the ordinary Series names nothing.** Forty-three of the ninety-seven
-- Volumes in this library belong to no Series at all, and a Series that names no Story
-- behaves exactly as it did yesterday.
--
-- **The ledger stays a ledger.** The arrow states what is printed and never whether it was
-- any good — there is no Rating here and there never will be, because a Series answers
-- *what am I missing* and a Story answers *was it any good* (ADR-0001).
--
-- `on delete set null` rather than a refusal: striking a Story is refused while an object in
-- the house carries it, a Reading went through it, it was judged or a Path names it
-- (ADR-0015), and a Series is none of those. One that outlives the Story it named is a
-- ledger that has stopped saying what it prints, which is where every Series stood before
-- this migration — nothing about the shelf, the count published or the missing list moves.
--
-- Generated by `drizzle-kit generate` and then hand-finished: the `comment on` below is the
-- part Drizzle does not write, and it is where this schema documents itself (ADR-0009). The
-- **number is the one exception to "you do not pick a number"** (README): five slices of #34
-- were written in parallel worktrees off one base, and the owner reserved a prefix to each
-- so that five generators could not all write `0005_`. The generator produced this file as
-- `0005_`; the tag and the journal's `idx` were then moved to the reserved slot, and its
-- `when` was set after the four reserved before it so that the timestamp Drizzle applies by
-- agrees with the order the journal lists.

ALTER TABLE "series" ADD COLUMN "story_id" uuid;--> statement-breakpoint
ALTER TABLE "series" ADD CONSTRAINT "series_story_exists" FOREIGN KEY ("story_id") REFERENCES "public"."story"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "series_by_story" ON "series" USING btree ("story_id");--> statement-breakpoint

COMMENT ON COLUMN public.series.story_id IS 'Which Story this Series publishes - the one arrow between the ledger and the narrative. Many Series may name one Story, because two editions of one Story are two ledgers and one narrative. Null is the ordinary case, and a Series that names none behaves as it always has. It says what is printed and never whether it was any good.'
