-- **A pin names the thing to read**, and no longer the source it came from (#40, #34).
--
-- The Reading list becomes two halves — a head the owner pinned, in pin order, and a
-- reserve that composes itself and is deliberately unordered — and the pin is what
-- separates them. That is only sayable if a pin points at an *entry*, and an entry is now
-- keyed by the thing to read: a **Story**, or a **position of a Series**.
--
-- What it replaces, and why the old subject could not stay. A pin named a Path or a Series,
-- and a route contributed exactly one stop, so *three Marvel stories and then a DC one* had
-- nowhere to be written down: pinning Marvel pinned whatever Marvel happened to be offering,
-- and the second and third stop of that route could not be reached at all. It also could not
-- survive the dedup this slice brings — one Story is one row however many reasons put it
-- there, so a row that is wanted *and* on two routes has three sources and could not be
-- addressed by any one of them.
--
--   * **`story_id`** — the narrative to read. One pin per Story, because one Story is one
--     row; cascading, because a Story struck from the library has no place left on a list
--     (ADR-0015).
--   * **`series_id` + `series_position`** — the shopping half, which names an *object* and no
--     narrative (ADR-0001), so the line alone does not identify it: the entry is *Death Note
--     Black Edition 2* and not *Death Note Black Edition*. One pin per position of a line.
--   * **exactly one of the two, and Postgres says so** rather than an `if` in a verb. A
--     Series pin without a position is not a subject at all, which is the second check; the
--     third is that a position is a place in a line, counted from one.
--
-- `path_id` goes, and the pins standing on it are **carried across rather than dropped**: the
-- owner does nothing, and what they pinned yesterday is still at the front tomorrow. A pin on
-- a Path becomes a pin on the Story that route was offering — its first stop with no Reading
-- at all, which is what `to-read` means in `src/core/queries/story.ts` — and a pin on a Series
-- gains the position that line was offering, the first the house does not hold. A pin whose
-- subject had nothing left to offer is deleted, and loses nothing: a route walked out or put
-- aside contributed no entry yesterday either.
--
-- Generated by `drizzle-kit generate` and then hand-finished, which here is three things: the
-- backfill in the middle, which Drizzle cannot know about, the `comment on` statements, which
-- are where this schema documents itself (ADR-0009), and the number. The **number is the same
-- exception #34's other slices took** (README): several slices of one tracker were written in
-- parallel worktrees off one base, and the owner reserved a prefix to each so that two
-- generators could not write `0010_` at once. The generator produced this file as
-- `0010_melodic_ezekiel`; the tag was renamed for what it does, and its `when` set after
-- `0009`'s so that the timestamp Drizzle applies by agrees with the order the journal lists.

ALTER TABLE "reading_list_pin" DROP CONSTRAINT "reading_list_pin_has_one_subject";--> statement-breakpoint
ALTER TABLE "reading_list_pin" DROP CONSTRAINT "reading_list_pin_path_exists";
--> statement-breakpoint
DROP INDEX "reading_list_pin_one_per_path";--> statement-breakpoint
DROP INDEX "reading_list_pin_one_per_series";--> statement-breakpoint
ALTER TABLE "reading_list_pin" ADD COLUMN "story_id" uuid;--> statement-breakpoint
ALTER TABLE "reading_list_pin" ADD COLUMN "series_position" integer;--> statement-breakpoint

-- The pins the owner already has, moved onto the new subject. Between the columns arriving
-- and the old one leaving, which is the only moment both subjects exist.

-- A pin on a Path becomes a pin on the Story that route was offering: its first stop nothing
-- has been read of, in the owner's own order.
UPDATE reading_list_pin p
   SET story_id = (
     SELECT i.story_id
       FROM path_item i
      WHERE i.path_id = p.path_id
        AND NOT EXISTS (SELECT 1 FROM reading r WHERE r.story_id = i.story_id)
      ORDER BY i.position
      LIMIT 1
   )
 WHERE p.path_id IS NOT NULL;--> statement-breakpoint

-- A pin on a Series gains the position that line was offering: the first the house does not
-- hold, which is what the ledger calls missing.
UPDATE reading_list_pin p
   SET series_position = (
     SELECT n
       FROM generate_series(1, s.published_count) AS n
      WHERE NOT EXISTS (
        SELECT 1
          FROM volume v
         WHERE v.series_id = s.id
           AND v.series_number = n
           AND EXISTS (SELECT 1 FROM acquisition a
                        WHERE a.volume_id = v.id AND a.released_on IS NULL)
      )
      ORDER BY n
      LIMIT 1
   )
  FROM series s
 WHERE s.id = p.series_id;--> statement-breakpoint

-- A pin whose subject had nothing to offer goes. It contributed no entry yesterday either —
-- the route is walked out or put aside, or the line is complete — so nothing the owner could
-- see is lost with it.
DELETE FROM reading_list_pin WHERE path_id IS NOT NULL AND story_id IS NULL;--> statement-breakpoint
DELETE FROM reading_list_pin WHERE series_id IS NOT NULL AND series_position IS NULL;--> statement-breakpoint

-- Two routes can offer the same Story, and one Story is one row now: the newer pin is the
-- more recent decision and it is the one that stands.
DELETE FROM reading_list_pin p
 USING reading_list_pin q
 WHERE p.story_id IS NOT NULL
   AND p.story_id = q.story_id
   AND (q.pinned_at > p.pinned_at OR (q.pinned_at = p.pinned_at AND q.ctid > p.ctid));--> statement-breakpoint

ALTER TABLE "reading_list_pin" ADD CONSTRAINT "reading_list_pin_story_exists" FOREIGN KEY ("story_id") REFERENCES "public"."story"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "reading_list_pin_one_per_story" ON "reading_list_pin" USING btree ("story_id") WHERE (story_id IS NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX "reading_list_pin_one_per_series_position" ON "reading_list_pin" USING btree ("series_id","series_position") WHERE (series_id IS NOT NULL);--> statement-breakpoint
ALTER TABLE "reading_list_pin" DROP COLUMN "path_id";--> statement-breakpoint
ALTER TABLE "reading_list_pin" ADD CONSTRAINT "reading_list_pin_a_series_pin_names_a_position" CHECK ((series_id IS NULL) = (series_position IS NULL));--> statement-breakpoint
ALTER TABLE "reading_list_pin" ADD CONSTRAINT "reading_list_pin_a_position_is_a_place_in_the_line" CHECK ((series_position IS NULL) OR (series_position >= 1));--> statement-breakpoint
ALTER TABLE "reading_list_pin" ADD CONSTRAINT "reading_list_pin_has_one_subject" CHECK ((story_id IS NULL) <> (series_id IS NULL));--> statement-breakpoint

COMMENT ON TABLE public.reading_list_pin IS 'The only thing the Reading list stores. The list composes itself from the Wants, the active Paths and the Series being collected and is a table nowhere; a pin is the owner''s own order over it, and it names the thing to read - a Story, or a position of a Series - rather than the source that offered it. The pinned rows are the list''s head, in pin order; everything else is the reserve, which nobody keeps in order.';--> statement-breakpoint

COMMENT ON COLUMN public.reading_list_pin.story_id IS 'The narrative to read. One pin per Story, because one Story is one row on the list however many reasons put it there - wanted, and on two routes, is one entry naming all three.';--> statement-breakpoint

COMMENT ON COLUMN public.reading_list_pin.series_id IS 'The line the pinned object stands in. It takes a position beside it, because the shopping half of the list names an object and not a narrative.';--> statement-breakpoint

COMMENT ON COLUMN public.reading_list_pin.series_position IS 'Which position of that line: the entry is Death Note Black Edition 2 and not Death Note Black Edition. Null exactly when the pin names a Story.';--> statement-breakpoint

COMMENT ON COLUMN public.reading_list_pin.pinned_at IS 'The most recently pinned comes first: pinning is the act of saying "this next", so the head reads newest decision first.'
