-- The count of Instalments follows the line, and one column says whose word it is (#34).
--
-- Setting a Series' published count and then being asked *again* how many Instalments the
-- work has is two questions about one number. They are not the same fact —
-- `series.published_count` is a **printing's** and `story.instalments` is the
-- **narrative's** — but on these shelves the two coincide for almost every record, so the
-- second question reads as a re-ask. #34 promised that where a line prints one part per
-- Volume the Instalments *follow the volumes*, and only the per-Volume ranges were built
-- that way: the count still had to be typed.
--
-- **So the count follows the line, and this is the one new fact it takes.**
-- `story.instalments_said_by` says whose number stands there — `line` for a count the
-- library keeps in step with the Series that publishes the work, `owner` for one the owner
-- gave, null for a work nobody has numbered. Without it rule 3 below cannot be told from
-- rule 1, because a hand correction to the number the line happens to give is
-- indistinguishable from the following itself.
--
-- The rule, in five clauses (ADR-0017):
--
--   1. exactly one Series names the Story and its published count is above nought → the
--      Story's count **is** that number, and stays at it as the line grows: an ongoing line
--      gains volumes, and the work gains parts
--   2. `published_count = 0` means *the owner never filled it in*, not *zero parts*. Such a
--      work declares nothing, exactly as before this migration
--   3. the owner correcting the count by hand stops the following **permanently** — from
--      then on the number is their word, and `instalments_said_by = 'owner'` is that
--   4. two or more Series naming one Story → no following at all. The number stops moving
--      and becomes the owner's, because which of two ledgers a narrative takes its length
--      from is not something this library decides for them
--   5. a line that stops answering — deleted, repointed, or corrected down to nought —
--      **freezes** the number rather than taking it away. Nothing the owner has read a
--      fraction against disappears behind their back
--
-- **It is a column kept by a trigger rather than a derivation at read time**, and the reason
-- is load-bearing. The two invariants #34 insisted be constraints rather than `if`s — a pass
-- cannot stand past the end of the work, and a Volume's covered range cannot fall outside it
-- — are `an_instalment_lies_inside_the_work()` and `the_work_still_holds_what_was_read()`
-- over `story.instalments` (migration 0007). Derive the count at read time and those
-- constraints bite only on works where the number was typed. Cross-table invariants are
-- already triggers in this schema, and this is the same idiom pointed the other way: 0007's
-- triggers refuse a write that would break the count, and this one *writes* the count.
--
-- Two functions rather than one, and it is 0007's reason again: PL/pgSQL resolves the fields
-- of `old` and `new` against whichever event fired the trigger, so `old.story_id` written in
-- a body that also runs on `insert` fails there even where a `tg_op` guard means it is never
-- reached. So the trigger reads the two ids it can see and the recompute is a function of one
-- Story.
--
-- The migration applies the rule to what already stands: a work whose single line has a
-- count above nought and which declares none takes that count and is marked as following; a
-- count already typed stays the owner's word.
--
-- Generated by `drizzle-kit generate` and then hand-finished: the two functions, the trigger,
-- the backfill and every `comment on` below are the part Drizzle does not write (ADR-0009).

ALTER TABLE "story" ADD COLUMN "instalments_said_by" text;--> statement-breakpoint

-- **The backfill comes before the constraints**, because it is what makes them true of the
-- library as it stands: every count already there is somebody's word by the end of it.
UPDATE "story" s
   SET instalments = l.published_count,
       instalments_said_by = 'line'
  FROM (SELECT story_id, count(*) AS lines, max(published_count) AS published_count
          FROM series
         WHERE story_id IS NOT NULL
         GROUP BY story_id) l
 WHERE l.story_id = s.id
   AND l.lines = 1
   AND l.published_count > 0
   AND s.instalments IS NULL;--> statement-breakpoint

UPDATE "story" SET instalments_said_by = 'owner'
 WHERE instalments IS NOT NULL AND instalments_said_by IS NULL;--> statement-breakpoint

ALTER TABLE "story" ADD CONSTRAINT "story_instalments_are_said_by_the_owner_or_the_line" CHECK ((instalments_said_by IS NULL) OR (instalments_said_by = ANY (ARRAY['owner'::text, 'line'::text])));--> statement-breakpoint
ALTER TABLE "story" ADD CONSTRAINT "story_instalments_carry_whose_word_they_are" CHECK ((instalments IS NULL) OR (instalments_said_by IS NOT NULL));--> statement-breakpoint
ALTER TABLE "story" ADD CONSTRAINT "story_the_lines_count_is_a_number" CHECK ((instalments_said_by IS DISTINCT FROM 'line'::text) OR (instalments IS NOT NULL));--> statement-breakpoint

CREATE FUNCTION public.the_count_the_lines_give(work uuid) RETURNS void
    LANGUAGE plpgsql
    AS $$
declare
  lines   integer;
  printed integer;
begin
  -- A Series that names no Story changed, which is most of them: there is no work to answer
  -- for.
  if work is null then
    return;
  end if;

  select count(*), max(published_count) into lines, printed
    from series where story_id = work;

  if lines = 1 and printed > 0 then
    -- The line answers, so the count is the line's. Refused where the owner has spoken,
    -- which is what makes a hand correction permanent, and left alone where it already
    -- stands at that number, so an untouched work is not written to on every ledger edit.
    update story s
       set instalments = printed,
           instalments_said_by = 'line'
     where s.id = work
       and s.instalments_said_by is distinct from 'owner'
       and (s.instalments is distinct from printed
            or s.instalments_said_by is distinct from 'line');
  else
    -- No line answers it any more — nought published, two ledgers, or none at all. The
    -- number is **frozen and handed to the owner** rather than taken away: a fraction the
    -- owner has been reading against must not vanish because a ledger was edited, and which
    -- of two lines a narrative takes its length from is theirs to say.
    update story s
       set instalments_said_by = 'owner'
     where s.id = work
       and s.instalments_said_by = 'line';
  end if;
end;
$$;--> statement-breakpoint

COMMENT ON FUNCTION public.the_count_the_lines_give(uuid) IS 'Puts one Story''s count of Instalments back in step with the Series that publish it (#34): the line''s number where exactly one line answers, frozen as the owner''s word where none does, and never touched where the owner has corrected it by hand.';--> statement-breakpoint

CREATE FUNCTION public.the_count_follows_the_line() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  -- Both ends of the change, because a ledger repointed from one work to another changes the
  -- length of two: `old` on a delete and an update, `new` on an insert and an update. They
  -- are read in two statements rather than in one expression for the reason 0007 splits its
  -- own function — a body naming `old.story_id` fails on the insert event whatever guards it.
  if tg_op <> 'INSERT' then
    perform the_count_the_lines_give(old.story_id);
  end if;

  if tg_op <> 'DELETE' then
    perform the_count_the_lines_give(new.story_id);
  end if;

  return null;
end;
$$;--> statement-breakpoint

COMMENT ON FUNCTION public.the_count_follows_the_line() IS 'The count of Instalments follows the line that publishes the work (#34). It fires on the arrow and on the published count, which are the two facts the following is made of.';--> statement-breakpoint

CREATE TRIGGER series_says_how_long_the_work_is
    AFTER INSERT OR DELETE OR UPDATE OF story_id, published_count ON public.series
    FOR EACH ROW EXECUTE FUNCTION public.the_count_follows_the_line();--> statement-breakpoint

COMMENT ON COLUMN public.story.instalments_said_by IS 'Whose word the count of Instalments is: "line" where it follows the Series that publishes this work and moves as that line grows, "owner" where they gave or corrected it and nothing moves it again, null where nobody has numbered it (#34). It is the one fact the following needs stored - without it a hand correction cannot be told from the line''s own answer.';--> statement-breakpoint

COMMENT ON COLUMN public.story.instalments IS 'How many Instalments this Story has, where it was serialized: Slam Dunk''s twenty. Null is not serialized at all, which is the ordinary case - a one-shot is never asked (#37). It belongs to the narrative and never to a printing, so it is true however the owner read them. Where exactly one Series names this Story and has published more than nought, it is that line''s count and follows it as the line grows; instalments_said_by says which (#34).'
