-- **The database calls a pass a Pass**, and the Reading list the Pile (#56, #55).
--
-- `CONTEXT.md` had stopped using the old word before this migration was written — it says
-- *a pass* four times inside the entry that used to define a Reading — because a Reading is
-- *one act of reading a Story* and a videogame is not read. The glossary now says **Pass**,
-- and **the Pile** for what the owner takes on next, and this is the schema catching up
-- (ADR-0021).
--
-- **This is the expand half of an expand-contract rename**, and the half of it a database can
-- do. `db/schema.ts` re-exports `reading` and `readingListPin` as aliases of `pass` and
-- `pilePin`, so anything typed from the schema module goes on describing the same rows.
-- Nothing else does: the queries above `db/` are SQL text and not a builder (ADR-0009), so
-- they name these tables, `rating.reading_id` and half these constraints in strings, which no
-- alias reaches. **Until the contract step (#57) renames them, the repository does not run
-- against this schema.** That is the shape of the rename and not an accident of this file —
-- there is no version of it in which a table has both names at once.
--
-- **Renamed rather than recreated, everywhere it could be.** `drizzle-kit generate` writes a
-- rename of the two tables and the one column and then drops and re-adds every constraint and
-- index whose name changed with them. The end state is the same and the cost is not: a dropped
-- and re-added check or foreign key is revalidated against the whole table, and for the length
-- of one statement the invariant is not there at all. `ALTER TABLE ... RENAME CONSTRAINT` and
-- `ALTER INDEX ... RENAME` are catalogue edits — no rewrite, no revalidation, no window. The
-- generated drop/add pairs were replaced by them; nothing else about the file's end state
-- differs, so the snapshot Drizzle wrote beside it is still the description the next diff is
-- taken against.
--
-- **Production holds real data and none of it moves.** A rename in Postgres is atomic and
-- touches no row: 96 Stories, 45 passes and 40 Ratings are the same rows under the new words,
-- with no backfill, no copy and no moment where a record is missing.
--
-- The applied migrations behind this one go on saying `reading` for ever. They are
-- forward-only and hashed and are never edited; what they say is what was true when they ran.
--
-- **The journal's `when` was moved forward**, which is the exception `0010` took and for its
-- reason: `0012` reserved a round timestamp a day ahead of the clock, so the honest one the
-- generator wrote here sorted behind a migration that runs before it. The tag and the order
-- are the generator's; only the timestamp was corrected, so that the moment Drizzle applies
-- by agrees with the order the journal lists.
--
-- Generated by `drizzle-kit generate` and then hand-finished, which here is four things: the
-- renames above, the not-null constraints Drizzle does not model, the two PL/pgSQL functions
-- that name the table in their bodies, and every `comment on`, which is where this schema
-- documents itself (ADR-0009).

ALTER TABLE "reading" RENAME TO "pass";--> statement-breakpoint
ALTER TABLE "reading_list_pin" RENAME TO "pile_pin";--> statement-breakpoint
ALTER TABLE "rating" RENAME COLUMN "reading_id" TO "pass_id";--> statement-breakpoint

-- The furniture. A constraint or an index whose name still said `reading` would leave the
-- schema explaining itself in two vocabularies, and the name a refusal quotes is the one a
-- reader meets first.

ALTER TABLE "pass" RENAME CONSTRAINT "reading_pkey" TO "pass_pkey";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_id_and_story" TO "pass_id_and_story";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_story_exists" TO "pass_story_exists";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_provenance_exists" TO "pass_provenance_exists";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_volume_exists" TO "pass_volume_exists";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_digital_went_through_no_volume" TO "pass_digital_went_through_no_volume";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_medium_is_paper_or_digital" TO "pass_medium_is_paper_or_digital";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_outcome_is_finished_or_abandoned" TO "pass_outcome_is_finished_or_abandoned";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_unconcluded_has_not_ended" TO "pass_unconcluded_has_not_ended";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_did_not_end_before_it_started" TO "pass_did_not_end_before_it_started";--> statement-breakpoint
ALTER TABLE "pass" RENAME CONSTRAINT "reading_at_instalment_is_positive" TO "pass_at_instalment_is_positive";--> statement-breakpoint
ALTER INDEX "reading_by_story" RENAME TO "pass_by_story";--> statement-breakpoint

ALTER TABLE "pile_pin" RENAME CONSTRAINT "reading_list_pin_story_exists" TO "pile_pin_story_exists";--> statement-breakpoint
ALTER TABLE "pile_pin" RENAME CONSTRAINT "reading_list_pin_series_exists" TO "pile_pin_series_exists";--> statement-breakpoint
ALTER TABLE "pile_pin" RENAME CONSTRAINT "reading_list_pin_has_one_subject" TO "pile_pin_has_one_subject";--> statement-breakpoint
ALTER TABLE "pile_pin" RENAME CONSTRAINT "reading_list_pin_a_series_pin_names_a_position" TO "pile_pin_a_series_pin_names_a_position";--> statement-breakpoint
ALTER TABLE "pile_pin" RENAME CONSTRAINT "reading_list_pin_a_position_is_a_place_in_the_line" TO "pile_pin_a_position_is_a_place_in_the_line";--> statement-breakpoint
ALTER INDEX "reading_list_pin_one_per_story" RENAME TO "pile_pin_one_per_story";--> statement-breakpoint
ALTER INDEX "reading_list_pin_one_per_series_position" RENAME TO "pile_pin_one_per_series_position";--> statement-breakpoint

-- The two on `rating`, which is not renamed and holds the arrow. A judgement hangs off the
-- Pass it was made after (ADR-0018), so both of these names followed the word.
ALTER TABLE "rating" RENAME CONSTRAINT "rating_belongs_to_the_read_story" TO "rating_belongs_to_the_story_passed_through";--> statement-breakpoint
ALTER TABLE "rating" RENAME CONSTRAINT "rating_is_one_per_story_and_reading" TO "rating_is_one_per_story_and_pass";--> statement-breakpoint

-- The not-null constraints, which Postgres names after the table and Drizzle does not model.
-- A loop rather than a list of renames because the names are the server's and not ours: where
-- a server does not name them at all there is nothing to find, and this says so by finding
-- nothing instead of failing on a name that was never there.
DO $$
DECLARE named record;
BEGIN
  FOR named IN
    SELECT conname FROM pg_constraint
     WHERE conrelid = 'public.pass'::regclass AND contype = 'n' AND conname LIKE 'reading\_%'
  LOOP
    EXECUTE format('ALTER TABLE public.pass RENAME CONSTRAINT %I TO %I',
                   named.conname, 'pass_' || substring(named.conname from 9));
  END LOOP;

  FOR named IN
    SELECT conname FROM pg_constraint
     WHERE conrelid = 'public.pile_pin'::regclass AND contype = 'n'
       AND conname LIKE 'reading\_list\_pin\_%'
  LOOP
    EXECUTE format('ALTER TABLE public.pile_pin RENAME CONSTRAINT %I TO %I',
                   named.conname, 'pile_pin_' || substring(named.conname from 18));
  END LOOP;
END $$;--> statement-breakpoint

-- The trigger, and the two functions that name the table in their bodies. PL/pgSQL resolves a
-- table name when the function runs and not when it is created, so a rename that stopped at
-- the catalogue would leave both of these raising `relation "reading" does not exist` the next
-- time anybody wrote an Instalment. They are replaced whole rather than edited, which is what
-- ADR-0009 said would happen to any Postgres past the DSL.

ALTER TRIGGER "reading_at_instalment_lies_inside_the_work" ON "pass" RENAME TO "pass_at_instalment_lies_inside_the_work";--> statement-breakpoint

CREATE OR REPLACE FUNCTION public.an_instalment_lies_inside_the_work() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
  declared integer;
  reached  integer;
  covered  integer;
begin
  select s.instalments into declared from story s where s.id = new.story_id;

  -- Two branches rather than one expression, because PL/pgSQL resolves the fields of `new`
  -- against whichever row type fired the trigger: `new.covers_to` written beside
  -- `new.at_instalment` fails on the `pass` trigger even where it is never reached. The
  -- same reason 0000 splits `volume_holds_one_position()`.
  if tg_table_name = 'pass' then
    reached := new.at_instalment;

    -- Nothing said about how far it got, which is the ordinary pass.
    if reached is null then
      return null;
    end if;

    if declared is null then
      raise exception 'that Story has no Instalments to be at'
        using errcode = 'check_violation',
              constraint = 'pass_at_instalment_needs_a_serialized_story';
    end if;

    if reached > declared then
      raise exception 'that pass got further than the work goes'
        using errcode = 'check_violation',
              constraint = 'pass_at_instalment_is_within_the_work';
    end if;
  else
    covered := new.covers_to;

    -- No range written by hand, so the range follows the object's position in its line.
    if covered is null then
      return null;
    end if;

    if declared is null then
      raise exception 'that Story has no Instalments to cover'
        using errcode = 'check_violation',
              constraint = 'volume_story_cover_needs_a_serialized_story';
    end if;

    if covered > declared then
      raise exception 'that object covers past the end of the work'
        using errcode = 'check_violation',
              constraint = 'volume_story_cover_lies_inside_the_work';
    end if;
  end if;

  return null;
end;
$$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION public.the_work_still_holds_what_was_read() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  if new.instalments is not distinct from old.instalments then
    return null;
  end if;

  -- Shortening a work, or taking its numbering away altogether, is refused while a pass or
  -- an object stands beyond the new end. Otherwise the invariant above would hold only at
  -- the moment it was written, and *seven of five* would be reachable by editing the five.
  if exists (
    select 1 from pass r
     where r.story_id = new.id
       and r.at_instalment is not null
       and (new.instalments is null or r.at_instalment > new.instalments)
  ) then
    raise exception 'a pass through it got further than that'
      using errcode = 'check_violation',
            constraint = 'story_instalments_still_hold_what_was_read';
  end if;

  if exists (
    select 1 from volume_story vs
     where vs.story_id = new.id
       and vs.covers_to is not null
       and (new.instalments is null or vs.covers_to > new.instalments)
  ) then
    raise exception 'an object covers further than that'
      using errcode = 'check_violation',
            constraint = 'story_instalments_still_hold_what_is_covered';
  end if;

  return null;
end;
$$;--> statement-breakpoint

-- The prose. A comment is carried across a rename untouched, which is how a schema ends up
-- documenting itself in a vocabulary it no longer uses. Every one on the two renamed tables
-- and on the renamed column is rewritten, and the two on the functions above with them.

COMMENT ON TABLE public.pass IS 'One pass through a Story: an event, never a status field. Several for the same Story is the ordinary case, because going through something a second time is. What it went by is the medium, and what it ended as is the outcome.';--> statement-breakpoint

COMMENT ON COLUMN public.pass.outcome IS 'finished or abandoned; null while the pass is still under way.';--> statement-breakpoint

COMMENT ON COLUMN public.pass.volume_id IS 'The object the pass went through, where there was one. Null is the ordinary case: going through something and owning it are unrelated facts.';--> statement-breakpoint

COMMENT ON COLUMN public.pass.at_instalment IS 'The last Instalment this pass finished, which is what answers "seven of twenty" without a progress field on the Story (#37). Null on an unstarted or unnumbered pass. It is on the pass because how far you got is a fact about an event, and it survives changing edition halfway.';--> statement-breakpoint

COMMENT ON TABLE public.pile_pin IS 'The only thing the Pile stores. The Pile composes itself from the Wants, the active Paths and the Series being collected and is a table nowhere; a pin is the owner''s own order over it, and it names the thing to take on next - a Story, or a position of a Series - rather than the source that offered it. The pinned rows are the Pile''s head, in pin order; everything else is the reserve, which nobody keeps in order.';--> statement-breakpoint

COMMENT ON COLUMN public.pile_pin.story_id IS 'The narrative to take on next. One pin per Story, because one Story is one row on the Pile however many reasons put it there - wanted, and on two routes, is one entry naming all three.';--> statement-breakpoint

COMMENT ON COLUMN public.pile_pin.series_id IS 'The line the pinned object stands in. It takes a position beside it, because the shopping half of the Pile names an object and not a narrative.';--> statement-breakpoint

COMMENT ON COLUMN public.pile_pin.series_position IS 'Which position of that line: the entry is Death Note Black Edition 2 and not Death Note Black Edition. Null exactly when the pin names a Story.';--> statement-breakpoint

COMMENT ON COLUMN public.pile_pin.pinned_at IS 'The most recently pinned comes first: pinning is the act of saying "this next", so the head reads newest decision first.';--> statement-breakpoint

COMMENT ON COLUMN public.rating.pass_id IS 'The Pass this judgement was made after, where it was made after one. Null is a judgement on the narrative itself rather than on one way through it, which is why the pair is unique with nulls counted alike.';--> statement-breakpoint

COMMENT ON FUNCTION public.an_instalment_lies_inside_the_work() IS 'An Instalment a Pass reached, and a range an object covers, both lie inside the Story they are about (#37). A check constraint cannot read another table, so this is the constraint restated across two of them.';--> statement-breakpoint

COMMENT ON FUNCTION public.the_work_still_holds_what_was_read() IS 'A Story cannot be shortened past what a Pass has gone through of it or what an object covers of it (#37) - otherwise "seven of five" is reachable by editing the five.'
