-- The medium is a vocabulary, and only paper goes through an object (#61, ADR-0022).
--
-- `pass.medium` was two values written into a check constraint. It becomes a **table of
-- data**, beside Type, Binding, Provenance and credit_role: the console a game was played on
-- is a medium standing on the same axis as paper and digital, and a console released next
-- year is an insert rather than a migration.
--
-- The rule the old constraint carried moves with it. `pass_digital_went_through_no_volume`
-- said *a pass through a Volume is a pass on paper*, by naming the one value that was not
-- allowed to go through an object. With a list that grows, that sentence cannot live in a
-- constraint over values: each medium **declares whether it can go through an object**, in
-- `goes_through_an_object`, and only paper does. No console can, which is the same fact the
-- old rule stated, said in a way that survives a fourth console.
--
-- **Nothing about this library changes today.** Two rows are seeded and they are the two
-- values the constraint held, carrying the flag it implied; every Pass already standing
-- points at one of them, and the invariant refuses exactly what it refused before. What
-- changes is where the list lives.
--
-- The order of the statements is the whole of the migration's correctness, and it is one
-- transaction: the rows exist before the foreign key that points at them, and the invariant
-- is put back before the check it replaces is taken away — so there is no instant, even
-- inside the transaction, at which a pass through an object could be recorded by a medium
-- that does not go through one.
--
-- **The invariant is a trigger** rather than a check, because a check constraint cannot read
-- another table and whether *this* medium goes through an object is a fact on the vocabulary
-- row. Cross-table invariants in this schema are triggers already —
-- `volume_holds_one_position()` since 0000, `an_instalment_lies_inside_the_work()` since 0007
-- — so this follows the house style rather than introducing one (ADR-0009, ADR-0017). It
-- raises with a constraint name, and `src/core/verbs/pass.ts` turns that name into the prose
-- the owner reads.
--
-- It fires where a **Pass** is written, which is where the old check fired and every write
-- there is. The vocabulary's own side is not guarded: a medium *added* cannot invalidate
-- anything, and taking the flag off a medium that passes have already gone through objects by
-- would — `the_work_still_holds_what_was_read()` in 0012 is the shape that rule would take.
-- Nothing writes that column today and no ticket has asked for a gesture that does, so it is
-- reported rather than invented here (#61).
--
-- Generated by `drizzle-kit generate` and then hand-finished: the seeded rows, the order
-- above, the function, its trigger and every `comment on` are the part Drizzle does not
-- write (ADR-0009).

CREATE TABLE "medium" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"display_order" integer NOT NULL,
	"goes_through_an_object" boolean NOT NULL,
	CONSTRAINT "medium_name_key" UNIQUE("name"),
	CONSTRAINT "medium_display_order_key" UNIQUE("display_order"),
	CONSTRAINT "medium_id_is_a_slug" CHECK (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text),
	CONSTRAINT "medium_name_is_not_blank" CHECK ((name = btrim(name)) AND (name <> ''::text)),
	CONSTRAINT "medium_display_order_is_positive" CHECK (display_order > 0)
);
--> statement-breakpoint

-- **The seeded list is the owner's, and it starts small** (ADR-0022). These two are the pair
-- the old check constraint held, and nothing else is added here: a medium nobody has gone
-- through anything by is a row nobody needs, and the consoles arrive when the owner says
-- which ones they play on. Rows are not schema, so `drizzle-kit generate` will never write
-- them (ADR-0006, ADR-0009) — every medium after these two is a hand-written file of its own,
-- exactly as a seventh Binding was.
--
-- They are **in this file rather than in one of their own**, which is the one place this
-- departs from the README's *each new vocabulary is a hand-written file*: the foreign key
-- below has to find them, and a migration is one transaction, so a separate file could only
-- come after the key it has to satisfy. The rule the README is stating is that rows are never
-- generated, and they are not — these two were typed.
INSERT INTO "medium" (id, name, display_order, goes_through_an_object) VALUES
  ('paper',   'Paper',   1, true),
  ('digital', 'Digital', 2, false);--> statement-breakpoint

ALTER TABLE "pass" ADD CONSTRAINT "pass_medium_exists" FOREIGN KEY ("medium") REFERENCES "public"."medium"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint

CREATE FUNCTION public.a_pass_through_an_object_went_by_a_medium_that_can() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
  through_an_object boolean;
begin
  -- A pass through no object is every digital pass, every borrowed one and every one known
  -- only from a history — the ordinary case, and there is nothing here to hold it to.
  if new.volume_id is null then
    return null;
  end if;

  select m.goes_through_an_object into through_an_object
    from medium m where m.id = new.medium;

  -- A medium this library does not know is `pass_medium_exists`' refusal and not this one, so
  -- the row is simply absent here and there is nothing left for this rule to say about it.
  if through_an_object is null or through_an_object then
    return null;
  end if;

  raise exception 'that medium does not go through an object'
    using errcode = 'check_violation',
          constraint = 'pass_through_an_object_went_by_a_medium_that_can';

  return null;
end;
$$;--> statement-breakpoint

COMMENT ON FUNCTION public.a_pass_through_an_object_went_by_a_medium_that_can() IS 'A Pass naming a Volume went by a medium that can go through an object, which today is paper alone (#61, ADR-0022). It is what the check constraint pass_digital_went_through_no_volume said while the list of media was closed; a check constraint cannot read the vocabulary row, so the rule is restated across the two tables.';--> statement-breakpoint

CREATE TRIGGER pass_through_an_object_went_by_a_medium_that_can
    AFTER INSERT OR UPDATE OF medium, volume_id ON public.pass
    FOR EACH ROW EXECUTE FUNCTION public.a_pass_through_an_object_went_by_a_medium_that_can();--> statement-breakpoint

-- The two hand-written rules, taken away only now that the one flag stands in their place.
ALTER TABLE "pass" DROP CONSTRAINT "pass_digital_went_through_no_volume";--> statement-breakpoint
ALTER TABLE "pass" DROP CONSTRAINT "pass_medium_is_paper_or_digital";--> statement-breakpoint

COMMENT ON TABLE public.medium IS 'What a Pass went through the Story by: paper, digital, or the console it was played on. A fact about the pass and never about the work - Hades on Switch and Hades on PC are one Story gone through twice. Stored as data so that a console released next year is an insert rather than a release (ADR-0022), which is the posture Type, Binding and Provenance already have (ADR-0006).';--> statement-breakpoint

COMMENT ON COLUMN public.medium.id IS 'Stable slug, and what MCP shows an external reader.';--> statement-breakpoint

COMMENT ON COLUMN public.medium.name IS 'What the owner reads on screen.';--> statement-breakpoint

COMMENT ON COLUMN public.medium.display_order IS 'The order the media are offered in.';--> statement-breakpoint

COMMENT ON COLUMN public.medium.goes_through_an_object IS 'Whether a pass by this medium can have gone through a Volume. True for paper alone: a console cannot, and neither can a file, because digital ownership is deliberately not modelled. It is the one column carrying the rule the check constraint pass_digital_went_through_no_volume stated by naming a value, and the Pile reads it too - what it takes to start something tonight is this medium needing no object, or the object being in the house (#61, ADR-0022).';--> statement-breakpoint

COMMENT ON COLUMN public.pass.medium IS 'What this pass went through the Story by, as a slug of the medium vocabulary. A pass that names a Volume went by a medium that goes through one, which the trigger above holds (#61, ADR-0022).'
