-- A Type offers the media it offers, and offered is not allowed (#63, ADR-0022).
--
-- `CONTEXT.md` says of a Type that it «decides which media are offered and nothing else»,
-- and until now nothing wrote that down: the two pickers that ask the question spelled
-- *paper* and *digital* into the markup, so choosing Videogame offered neither console and a
-- game's medium could be recorded through the MCP door alone. This is the table those
-- pickers read.
--
-- **It is a table rather than a map in code, and that is the whole decision here.** The
-- neighbouring shape, `theTypeEachBindingOffers`, keeps its two pairs in TypeScript and
-- argues for it: a row per Binding would read as *every Binding decides a Type*, and five of
-- the seven decide nothing. This mapping is the opposite on both counts — every Type has an
-- answer and every medium stands under some Type — and, more to the point, a map in code
-- naming `playstation-5` would make ADR-0022's promise false at the one screen it is about:
-- a console released next year would be an insert **and** a release, because the picker
-- would not offer what the vocabulary had gained. Here it is a second insert beside the
-- first, and no deployment.
--
-- **Nothing here refuses anything.** There is no foreign key from `pass` to this table and
-- no trigger reading it: a manga passed through on a PS5 is recorded exactly as it was
-- yesterday, because a vocabulary says what is offered and the owner is the one holding the
-- record. The only reader is a query behind two pickers.
--
-- **A Type with no row here is answered for anyway.** The query falls back to the whole
-- vocabulary rather than to an empty picker, which is also what stands in front of the owner
-- before they have chosen a Type at all — so the door with no script running offers every
-- medium and the write goes through (ADR-0010).
--
-- No display order of its own: what a picker offers is ordered by `medium.display_order`,
-- so a console inserted into the vocabulary takes its place here without a second number to
-- keep in step.
--
-- Generated by `drizzle-kit generate` and then hand-finished: the `comment on`s and the rows
-- are the part Drizzle does not write (ADR-0009). The rows are in this file rather than in
-- one of their own, unlike a vocabulary's, because this table says nothing empty — a mapping
-- with no rows is fifteen offers silently replaced by the fallback.

CREATE TABLE "type_medium" (
	"type_id" text NOT NULL,
	"medium_id" text NOT NULL,
	CONSTRAINT "type_medium_is_offered_once" PRIMARY KEY("type_id","medium_id")
);
--> statement-breakpoint
ALTER TABLE "type_medium" ADD CONSTRAINT "type_medium_type_exists" FOREIGN KEY ("type_id") REFERENCES "public"."type"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "type_medium" ADD CONSTRAINT "type_medium_medium_exists" FOREIGN KEY ("medium_id") REFERENCES "public"."medium"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

COMMENT ON TABLE public.type_medium IS 'Which media a Type offers: what is printed offers paper and digital, what is played offers the consoles (ADR-0022). It is read by the two pickers that ask the medium and by nothing else — offered is never allowed, so nothing in this schema refuses a Pass by a medium absent from this table. A Type with no row here is answered with the whole vocabulary rather than with an empty picker.';--> statement-breakpoint
COMMENT ON COLUMN public.type_medium.type_id IS 'The Type, which is chosen before the medium wherever both are asked for.';--> statement-breakpoint
COMMENT ON COLUMN public.type_medium.medium_id IS 'One medium offered for it. The order they are offered in is the vocabulary''s own display_order, so a console inserted there needs no second number here.';--> statement-breakpoint

-- **What is printed offers paper and digital.** The six Types the library had before a
-- videogame could be catalogued, each offered the pair the old check constraint held — which
-- is what both pickers already put in front of the owner, now said once as data instead of
-- twice as markup. **Play** is among them: a script is printed, and it arrived as an insert
-- the same way (migration 0013).
INSERT INTO type_medium (type_id, medium_id) VALUES
  ('manga',         'paper'),
  ('manga',         'digital'),
  ('comic',         'paper'),
  ('comic',         'digital'),
  ('graphic-novel', 'paper'),
  ('graphic-novel', 'digital'),
  ('novel',         'paper'),
  ('novel',         'digital'),
  ('non-fiction',   'paper'),
  ('non-fiction',   'digital'),
  ('play',          'paper'),
  ('play',          'digital');--> statement-breakpoint

-- **What is played offers the consoles**, and only the consoles. Neither paper nor digital
-- stands here, and the absent `digital` is the interesting one: a game carrying it beside a
-- console would be saying nothing twice, which is the argument ADR-0022 makes for the
-- console being the medium rather than a field beside it.
--
-- The three are the ones seeded in 0016, which are the ones in the owner's house. A fourth
-- console is two inserts — one into `medium`, one here — and that pair is what keeps the
-- promise that new hardware never needs a release.
INSERT INTO type_medium (type_id, medium_id) VALUES
  ('videogame', 'playstation-5'),
  ('videogame', 'nintendo-switch'),
  ('videogame', 'pc');
