-- A **Wish is planned into a month**, and the priority it used to carry is a ranking that
-- went stale (ADR-0023).
--
-- `priority` was 1 next, 2 soon, 3 someday: three words that say where a Wish stands
-- **relative to the others** and nothing about when the owner means to spend the money. A
-- relative ranking with three values and no order inside them ages in one direction —
-- everything the owner still means to buy drifts into *next*, and a list where twenty rows
-- are all *next* is the spreadsheet again.
--
-- A period is an **absolute** answer to the same question, and it is the sentence the owner
-- actually says: *this month I take these two, next month that one.* So the band a Wish
-- stands in is a month, and a Wish with **no** period is *someday* — the third priority,
-- kept as the absence of a plan rather than as a third word for one.
--
-- Three things about the shape:
--
--   * **it is a `date` and not a text month**, because it is compared against `current_date`
--     to know which band is this one and which are the ones that have gone by, and a
--     `YYYY-MM` string is a comparison waiting to be written by hand in three places. The two
--     doors talk in months — `to_char(period, 'YYYY-MM')` out, `to_date($1, 'YYYY-MM')` in —
--     and this column holds the first day of one, which `wish_period_is_a_month` is what
--     enforces;
--   * **it is nullable, and the null is a value the owner picks.** *Someday* is not a missing
--     period; it is the answer *not yet*, and it is why the shopping list has a band for it;
--   * **a month that has gone by is not a state.** Nothing here says late, overdue or
--     expired, and nothing ever will: a Wish planned into August and not bought in August is
--     still on the list in September, standing in its own band, which is the whole of what
--     the owner needs to see. A period is a plan and not a deadline the application enforces
--     — the posture a Declared constraint already takes.
--
-- The backfill is the only reading of the old three that is honest: *next* is the month the
-- owner is in, *soon* is the one after it, and *someday* is no month at all. It is applied to
-- every row, closed ones included, because a closed Wish is off the list and its period is
-- read by nobody — leaving them null would be a second rule to remember, where this is one.
--
-- Generated by `drizzle-kit generate` and then hand-finished: the backfill and the
-- `comment on` are the parts Drizzle does not write, and the second is where this schema
-- documents itself (ADR-0009).

ALTER TABLE "wish" ADD COLUMN "period" date;--> statement-breakpoint
ALTER TABLE "wish" ADD CONSTRAINT "wish_period_is_a_month" CHECK ((period IS NULL) OR (date_part('day'::text, (period)::timestamp without time zone) = (1)::double precision));--> statement-breakpoint

UPDATE public.wish
   SET period = CASE priority
                  WHEN 1 THEN date_trunc('month', CURRENT_DATE)::date
                  WHEN 2 THEN (date_trunc('month', CURRENT_DATE) + interval '1 month')::date
                  ELSE NULL
                END;--> statement-breakpoint

COMMENT ON COLUMN public.wish.period IS 'The month the owner means to buy it in, as the first day of that month. Null is `someday`: the absence of a plan, and a band of its own on the shopping list. A month that has gone by is not a state — nothing here says overdue.';
