-- The **priority goes**, now that a Wish is planned into a month (ADR-0023, migration 0020).
--
-- It is a separate file rather than the second half of that one because the two are separate
-- acts: 0020 writes a period for every Wish that had a priority, and this one takes away the
-- column that was read to write it. Applied together, they are one deploy; read apart, each
-- says one thing.
--
-- **Both are kept nowhere.** There is no *legacy priority* column and no view that answers
-- with one: two ways to say when a Wish is wanted would be two truths to keep in step by
-- hand, which is the failure the shopping list is most exposed to — it is read standing in a
-- shop, and a list ordered twice is a list the owner stops trusting.
--
-- Generated by `drizzle-kit generate`; nothing to hand-finish, because a dropped column takes
-- its own comment with it.

ALTER TABLE "wish" DROP CONSTRAINT "wish_priority_is_one_to_three";--> statement-breakpoint
ALTER TABLE "wish" DROP COLUMN "priority";
