import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// **THE JOURNAL HAS TO CLIMB**, and this is the wall that says so.
//
// Drizzle's migrator does not ask *which files has this database seen?* It reads the newest
// `created_at` in `drizzle.__drizzle_migrations` — one row per applied file, holding that
// file's `when` from this journal — and then applies every migration whose `when` is
// **greater** than that one number (`pg-core/dialect`, `lastDbMigration`). It is a watermark
// and not a set.
//
// So a `when` that sorts behind one already applied is a migration that will never run
// anywhere, and **nothing says so**: `pnpm db:migrate` reports success, a fresh database is
// built correctly from an empty table, every test passes, and the only surface that ever finds
// out is production — where the column is missing and the page is a 500. That is not a
// hypothesis: entries 12 to 18 were hand-written a day apart into the future, up to
// 2026-09-11, while 0019, 0020 and 0021 were generated by the clock on 7 and 8 September and
// therefore sorted **behind** a file already applied. Two deploys shipped code for a schema the
// database was never going to be given.
//
// It is a file-reading test and needs no database, which is the point: the failure is in the
// journal rather than in any schema, and a test that needed the schema could not see it.
const HERE = fileURLToPath(new URL(".", import.meta.url));

type Entry = { idx: number; when: number; tag: string };

const journal: { entries: Entry[] } = JSON.parse(
  readFileSync(new URL("./meta/_journal.json", import.meta.url), "utf8")
);

describe("the migration journal", () => {
  it("climbs, so that no migration sorts behind one already applied", () => {
    const behind = journal.entries.filter(
      (entry, at) => at > 0 && entry.when <= (journal.entries[at - 1]?.when ?? 0)
    );

    // Named rather than counted: what a reader needs is which file will be skipped and what
    // to set its `when` past.
    expect(behind.map((entry) => entry.tag)).toEqual([]);
  });

  // The other half of the same convention. `pnpm db:generate` names a file something random
  // and the README says rename it **and** the tag; a rename that touched one of the two leaves
  // the migrator reading a file that is not there, or leaves a file nothing will ever apply.
  it("names a file that exists, for every entry and every file", () => {
    const onDisk = readdirSync(HERE)
      .filter((name) => name.endsWith(".sql"))
      .map((name) => name.replace(/\.sql$/, ""))
      .sort();

    expect(journal.entries.map((entry) => entry.tag).sort()).toEqual(onDisk);
  });

  it("is in the order it is applied in", () => {
    const indices = journal.entries.map((entry) => entry.idx);

    expect([...indices].sort((one, other) => one - other)).toEqual(indices);
  });
});
