import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// **THE JOURNAL HAS TO CLIMB**, and this is the wall that says so.
//
// Drizzle's migrator keeps no set of files a database has seen. It reads the newest
// `created_at` in `drizzle.__drizzle_migrations` — one row per applied file, holding that
// file's `when` from this journal — and then applies every migration whose `when` is
// **greater** than that one number (`pg-core/dialect`, `lastDbMigration`). It is a watermark,
// not a set, and it is read once per run.
//
// So a `when` that sorts behind one already applied is a migration that will never run
// anywhere, and **nothing says so**: `pnpm db:migrate` reports success, a fresh database is
// built correctly because an empty table has no watermark, and every test passes for the same
// reason. The only surface that finds out is production, where the column is missing and the
// page is a 500. That is not a hypothesis — entries 12 to 18 were hand-written a day apart
// into the future, up to 2026-09-11, and 0020 and 0021 came from the real clock on 8 September
// and were skipped, so a deploy shipped code for a schema the database was never given.
//
// It reads files and needs no database, which is the point: the failure is in the journal
// rather than in any schema, and a test that needed the schema could not have seen it.
const HERE = fileURLToPath(new URL(".", import.meta.url));

type Entry = { idx: number; when: number; tag: string };

const journal: { entries: Entry[] } = JSON.parse(
  readFileSync(new URL("./meta/_journal.json", import.meta.url), "utf8")
);

/**
 * **The one entry that sits below the mark and has to stay there**, and it is a list of one
 * that nothing may join.
 *
 * 0019 was generated by the real clock while the database was at 0013, and applied then — so
 * every database that has it recorded `1788815344018` for it. Afterwards 0014 to 0018 landed
 * carrying timestamps a day apart in the *future*, which is what put the mark above it.
 *
 * Raising it now would not make it run anywhere: it would make it run **again**, on every
 * database that already has its columns, and fail on the first `add column` — taking the
 * migrations behind it down with it, which is exactly what this file exists to prevent. It was
 * tried, against a real database, and that is what happened.
 *
 * So the rule for anything **new** is the rule below, and this is the scar it is written
 * around: a migration is moved past the highest mark already applied, or it is left where the
 * databases recorded it. Never between.
 */
const ALREADY_APPLIED_BELOW_THE_MARK = ["0019_a_type_says_what_going_through_it_is_called"];

describe("the migration journal", () => {
  it("climbs, so that no migration sorts behind one already applied", () => {
    const behind: string[] = [];
    let mark = 0;

    for (const entry of journal.entries) {
      if (entry.when <= mark) behind.push(entry.tag);
      mark = Math.max(mark, entry.when);
    }

    // Named rather than counted: what a reader needs is *which* file will be skipped, and the
    // number to put its `when` past is the largest one above it.
    expect(behind).toEqual(ALREADY_APPLIED_BELOW_THE_MARK);
  });

  // The other half of the same convention. `pnpm db:generate` names a file something random
  // and the README says rename it **and** the tag; a rename that touched one of the two leaves
  // the migrator reading a file that is not there, or leaves a file nothing will ever apply.
  it("names a file that exists, for every entry and every file", () => {
    const onDisk = readdirSync(HERE)
      .filter((name) => name.endsWith(".sql"))
      .map((name) => name.replace(/\.sql$/, ""))
      .sort();

    expect(journal.entries.map((entry) => entry.tag).sort()).toEqual(onDisk);
  });

  it("is in the order it is applied in", () => {
    const indices = journal.entries.map((entry) => entry.idx);

    expect([...indices].sort((one, other) => one - other)).toEqual(indices);
  });
});
